<template >
  <div id="backstory" class="page-body">
    <div class="container">
      <p class="aftertitle">Certain values are weighted: a character has a 70% chance of having the same political, religious, or socio-economic status as parents/guardians.
        Any given character also has a 20% chance of a disability and a 50% chance of being of average intelligence. All other values are selected at random and independent of other results.</p>
      <div class="row extra-after">
        <div class="three columns"><button class="button" v-on:click="rollDice('one')">generate</button></div>
        <div class="three columns"><button class="button" v-on:click="rollDice('two')">generate</button></div>
        <div class="three columns"><button class="button" v-on:click="rollDice('three')">generate</button></div>
        <div class="three columns"><button class="button" v-on:click="rollDice('four')">generate</button></div>
      </div>
      <div class="row bordertop">
          <div class="three columns"><h5>Met protagonist...:</h5><p>{{backstory.one.intro}}</p></div>
          <div class="three columns"><h5>Met protagonist...:</h5><p>{{backstory.two.intro}}</p></div>
          <div class="three columns"><h5>Met protagonist...:</h5><p>{{backstory.three.intro}}</p></div>
          <div class="three columns"><h5>Met protagonist...:</h5><p>{{backstory.four.intro}}</p></div>
      </div>
      <div class="row bordertop">
          <div class="three columns"><h5>Family</h5><p>{{backstory.one.family}}</p></div>
          <div class="three columns"><h5>Family</h5><p>{{backstory.two.family}}</p></div>
          <div class="three columns"><h5>Family</h5><p>{{backstory.three.family}}</p></div>
          <div class="three columns"><h5>Family</h5><p>{{backstory.four.family}}</p></div>
      </div>
      <div class="row bordertop">
        <div class="three columns"><h5>Self</h5><p v-bind:key="d" v-for="d in backstory.one.ownself">{{d}}</p></div>
        <div class="three columns"><h5>Self</h5><p v-bind:key="d" v-for="d in backstory.two.ownself">{{d}}</p></div>
        <div class="three columns"><h5>Self</h5><p v-bind:key="d" v-for="d in backstory.three.ownself">{{d}}</p></div>
        <div class="three columns"><h5>Self</h5><p v-bind:key="d" v-for="d in backstory.four.ownself">{{d}}</p></div>
      </div>
      <div class="row bordertop">
        <div class="three columns"><h5>Other details</h5><p v-bind:key="d" v-for="d in backstory.one.life">{{d}}</p></div>
        <div class="three columns"><h5>Other details</h5><p v-bind:key="d" v-for="d in backstory.two.life">{{d}}</p></div>
        <div class="three columns"><h5>Other details</h5><p v-bind:key="d" v-for="d in backstory.three.life">{{d}}</p></div>
        <div class="three columns"><h5>Other details</h5><p v-bind:key="d" v-for="d in backstory.four.life">{{d}}</p></div>
      </div>
    </div>
  </div>
</template>

<script>
/*  eslint-disable quotes  */
export default {
  name: 'backstory',
  data: () => ({
    isActive: true,
    backstory: {
      one: {},
      two: {},
      three: {},
      four: {}
    },
    famstat1: null,
    famstat2: null,
    famstat3: null
  }),
  methods: {
    rollDice: function(val) {
      var dice = {
        intro: this.introsFactory(),
        family: this.familysFactory(),
        life: this.lifesFactory(),
        ownself: this.ownselfsFactory()
      }
      this.backstory[val] = dice;
    },
    shuffle: function(o) {
      for (var j, x, i = o.length; i; j = Math.floor(Math.random() * i), x = o[--i], o[i] = o[j], o[j] = x);
      return o;
    },
    introsFactory: function() {
      var introSet = this.shuffle(intros)[0] + ', and sees their relationship with the protagonist as ' + this.shuffle(attachments)[0] +
        '. Their interactions tend to be ' + this.shuffle(relationquals)[0] + '.';
      return introSet;
    },
    familysFactory: function() {
      this.famstat1 = this.shuffle(socioeconomics)[0];
      this.famstat2 = this.shuffle(politics)[0];
      this.famstat3 = this.shuffle(religions)[0];
      var familySet = 'This character was raised in ' + this.shuffle(familytypes)[0];
      num = Math.floor(Math.random() * (100) + 1);
      if (num < 10) {
        familySet += ' home, fostered by a ';
      } else if (num > 90) {
        familySet += ' orphanage run by a ';
      } else {
        familySet += ' ' + this.famstat1 + ' ';
      }
      num = Math.floor(Math.random() * (4) + 1);
      num > 3 ? familySet += this.shuffle(ethnicitys)[0] + '-' + this.shuffle(ethnicitys)[1] : familySet += this.shuffle(ethnicitys)[0];
      familySet += ' family. Influential family figures were ' + 'pro-' + this.famstat2 + ' and ' + this.shuffle(religstrengths)[0] + ' ' + this.famstat3 + '.';
      return familySet;
    },
    ownselfsFactory: function() {
      var arr = [];
      var selfSet1 = '';
      var selfSet2 = '';
      var selfSet3 = '';
      num = Math.floor(Math.random() * (10) + 1);
      if (num > 7) {
        selfSet3 += 'The character is ' + this.shuffle(socioeconomics)[0] + ', pro-' + this.shuffle(politics)[0] + ', and ' + this.shuffle(religstrengths)[0] + ' ' + this.shuffle(religions)[0] + '.';
      } else {
        selfSet3 += 'The character is ' + this.famstat1;
        num = Math.floor(Math.random() * (2) + 1);
        num > 1 ? selfSet3 += ', pro-' : selfSet3 += ', anti-';
        selfSet3 += this.famstat2 + ', and ' + this.shuffle(religstrengths)[0] + ' ' + this.famstat3 + '.';
      }
      arr.push(selfSet3);
      selfSet1 = 'The character has ';
      num = Math.floor(Math.random() * (8) + 1);
      if (num > 2) {
        selfSet1 += 'no formal education. ';
      } else {
        selfSet1 += this.shuffle(schoolings)[0] + ' education, focused on ' + this.shuffle(studies)[0] + ', and ' + this.shuffle(educations)[0] + '. '
      }
      selfSet1 += 'The character ';
      num = Math.floor(Math.random() * (10) + 1);
      if (num === 1) {
        selfSet1 += 'was recently laid-off from';
      } else if (num === 2) {
        selfSet1 += 'is retired from';
      } else {
        selfSet1 += 'is a ' + this.shuffle(works)[0] + ' in';
      }
      selfSet1 += ' the ' + this.shuffle(industrys)[0] + ' industry.';
      arr.push(selfSet1);
      selfSet2 = 'The character lives in ' + this.shuffle(interiors)[0] + ' ' + this.shuffle(lifes)[0];
      var num1 = Math.floor(Math.random() * (10) + 1);
      var num2 = Math.floor(Math.random() * (8) + 1);
      if (num1 > 5) {
        num = Math.floor(Math.random() * (5) + 1);
        num > 1 ? selfSet2 += ' with ' + num + ' ' + this.shuffle(coresidents)[0] + 's' : selfSet2 += ' with a ' + this.shuffle(coresidents)[0];
      }
      if (num2 > 4) {
        num1 > 5 ? selfSet2 += ' and ' : selfSet2 += ' with ';
        num = Math.floor(Math.random() * (5) + 1);
        num > 1 ? selfSet2 += num + ' ' + this.shuffle(pets)[0] + 's' : selfSet2 += ' with a ' + this.shuffle(pets)[0];
      }
      selfSet2 += '. The character ';
      num = Math.floor(Math.random() * (10) + 1);
      if (num > 5) {
        selfSet2 += 'is ' + this.shuffle(statusrels)[0] + ' a ' + this.shuffle(ethnicitys)[0] + ' ' + this.shuffle(types)[0] + ', and ';
      }
      num = Math.floor(Math.random() * (10) + 1);
      if (num === 1) {
        selfSet2 += 'is inexperienced at romance';
      } else {
        selfSet2 += 'has a history of being ' + this.shuffle(relationships)[0];
      }
      selfSet2 += '.';
      arr.push(selfSet2);
      return arr;
    },
    lifesFactory: function() {
      var arr = [];
      var lifeSet1 = '';
      var lifeSet2 = '';
      num = Math.floor(Math.random() * (12) + 1);
      if (num < 5) {
        num = Math.floor(Math.random() * (8) + 1);
        var instrument = this.shuffle(instruments);
        lifeSet1 += 'The character plays the ' + instrument[0] + ' ' + this.shuffle(ratequalitys)[0] + ', and ' + this.shuffle(approachs)[0] +
        ' play. As a ' + this.shuffle(gradestandings)[0] + ' musician, the character usually only plays ' + this.shuffle(usages)[0] + '. ';
        if (num < 3) {
          lifeSet1 += 'The character is also a ' + this.shuffle(gradestandings)[0] + ' with the ' + instrument[1] + ', and plays it ' +
          this.shuffle(ratequalitys)[0] + '. The character ' + this.shuffle(approachs)[0] + ' play, and only plays it ' + this.shuffle(usages)[0] + '.';
        }
      } else {
        lifeSet1 = 'The character does not play any musical instruments.';
      }
      num = Math.floor(Math.random() * (12) + 1);
      if (num < 5) {
        num = Math.floor(Math.random() * (3) + 1);
        var language = this.shuffle(languages);
        lifeSet2 += 'The character ' + this.shuffle(langskill)[0] + ' ' + language[0] + ' ' + this.shuffle(fluencys)[0] + ', and uses it ' + this.shuffle(usages)[0] + '. ';
        if (num === 2) {
          lifeSet2 += 'The character also ' + this.shuffle(langskill)[0] + ' ' + language[1] + ' ' + this.shuffle(fluencys)[0] + ', and uses it ' + this.shuffle(usages)[0] + '. ';
        }
      } else {
        lifeSet2 = 'The character does not speak any languages other than their native tongue.'
      }
      arr.push(lifeSet1, lifeSet2);
      return arr;
    }
  }
};
var num = 0;
var ethnicitys = [
  "Abenaki",
  "Abipone",
  "Abkhaz",
  "Abzinz",
  "Acadian",
  "Accohannock",
  "Acelmese",
  "Achang",
  "Acholi",
  "Achomawi",
  "Acoma",
  "Adi",
  "Adjarian",
  "Adyghe",
  "Adyhaffe",
  "Afar",
  "Afrikaner",
  "Aftsarian/Isaurian",
  "Agaw",
  "Agni",
  "Agta",
  "Agul",
  "Ahtna",
  "Aimaq",
  "Ainu",
  "Aja",
  "Ak Chin",
  "Aka",
  "Akan",
  "Akha",
  "Akhvakh",
  "Akie",
  "Akuapem",
  "Akyem",
  "Alabama",
  "Alak",
  "Albanian ",
  "Aleut",
  "Algonquian",
  "Aliutor",
  "Altaic",
  "Amahuaca",
  "Amamian",
  "Americo Liberian",
  "Amhara",
  "Amish",
  "Amungme",
  "Andalusian",
  "Andis",
  "Anga",
  "Anglo Indian",
  "Anglo Saxon",
  "Annamite",
  "Ansar/Ansarie",
  "Anuak",
  "Apache",
  "Apinaje",
  "Arab",
  "Arab Korean",
  "Aragonese",
  "Aramean Syriac",
  "Araon",
  "Arapaho",
  "Arawak",
  "Arbëreshë",
  "Archis",
  "Argentine",
  "Argentine",
  "Arikara",
  "Armenian",
  "Aromanian",
  "Arvanite",
  "Ashanti",
  "Asheninka",
  "Ashkenazi",
  "Asmat",
  "Assiniboine",
  "Assyrian",
  "Asturian",
  "Ati",
  "Atikamekw",
  "Atoni",
  "Atsina",
  "Atsugewi",
  "Atta",
  "Aukstaitian",
  "Australian Aborigine",
  "Austrian",
  "Avar",
  "Awá",
  "Aymara",
  "Aynu Chinese",
  "Ayta",
  "Azerbaijani",
  "Aztec",
  "Ba Na",
  "Baaster",
  "Babongo",
  "Badui",
  "Baggara",
  "Baguirmi",
  "Bagulal",
  "Bai",
  "Bajau",
  "Baka",
  "Bakhtiyari",
  "Bakongo/Kongo",
  "Balinese",
  "Balkar",
  "Baloch",
  "Baltic ",
  "Bamar",
  "Bambara",
  "Bamileke",
  "Banat Swabian",
  "Banawa",
  "Banda",
  "Bandjabi",
  "Bangladeshi ",
  "Banjar",
  "Bantu",
  "Baoule",
  "Bapou",
  "Bariba",
  "Bartang",
  "Basarwa",
  "Bashkir",
  "Basotho",
  "Basque",
  "Bassa",
  "Bassari",
  "Batak",
  "Bateke",
  "Bats",
  "Batswana",
  "Bavarian",
  "Baya Mandjia",
  "Beaver",
  "Bedouin",
  "Beja",
  "Belarusian",
  "Bemba",
  "Bengali",
  "Berber",
  "Beta Israel",
  "Betamaribe",
  "Bethio",
  "Beti Pahuin",
  "Bezhta",
  "Bhotiya",
  "Biafran",
  "Bicolano",
  "Black Indian",
  "Blackfoot",
  "Bo Y",
  "Boere Afrikaner",
  "Bolivian",
  "Bonairean",
  "Bonan",
  "Bosniak",
  "Botlikh",
  "Bouganvillean",
  "Boyar",
  "Boyko",
  "Bozo",
  "Brau",
  "Brazilian",
  "Breton",
  "British",
  "Brong",
  "Bru Van",
  "Brulé Kieu",
  "Bubi",
  "Budukh",
  "Bugis",
  "Bulang",
  "Bulgar",
  "Bunjevci",
  "Burmese",
  "Buryat",
  "Bushongo",
  "Buyi",
  "Caddo",
  "Cahuilla",
  "Caingang",
  "Cajun",
  "Caldoche",
  "Campa",
  "Canaanite",
  "Canadian",
  "Canadian",
  "Caprivian",
  "Carib",
  "Caribbean",
  "Carinthian",
  "Caripuna",
  "Castilian",
  "Catalan",
  "Catawba",
  "Cayuga",
  "Cayuse",
  "Ceylon",
  "Chagga",
  "Chaldean",
  "Cham",
  "Chamalal",
  "Chambri",
  "Chamorro",
  "Chechen",
  "Chehali",
  "Chemakum",
  "Chemehuevi",
  "Chepang",
  "Chere",
  "Cherokee",
  "Cheyenne",
  "Chicano",
  "Chickasaw",
  "Chilcotin",
  "Chilean",
  "Chinese ",
  "Chinookan",
  "Chipewyan",
  "Chippewa",
  "Chitimacha",
  "Cho Ro",
  "Choctaw",
  "Chukchansi",
  "Chukchi",
  "Chulym Tatar",
  "Chumash",
  "Chuncho",
  "Chut",
  "Chuukese",
  "Chuvash",
  "Ciboney",
  "Circassian",
  "Clayoquot",
  "Co",
  "Co Ho",
  "Co Lao",
  "Co Tu",
  "Coalhuiltec",
  "Coast Salish",
  "Cochiti",
  "Cocopah",
  "Coeur d'Alene",
  "Coharie",
  "Colchian",
  "Colombian",
  "Colville",
  "Comanche",
  "Comorian",
  "Cong",
  "Copper",
  "Coquille",
  "Cornish",
  "Cossack",
  "Costa Rican",
  "Costanoan",
  "Coushatta",
  "Cowichan",
  "Cowlitz",
  "Créole",
  "Cree",
  "Creek",
  "Crimean Goth",
  "Croat",
  "Croatian ",
  "Crow",
  "Cuban",
  "Cuman",
  "Cupeño",
  "Curaçaoan",
  "Cypriot",
  "Czech",
  "Daasanach",
  "Dadhich",
  "Thai",
  "Dajak",
  "Dakelh",
  "Dakota",
  "Damara",
  "Danish",
  "Danmin",
  "Dargin",
  "Darhad",
  "Daribi",
  "Daur",
  "De'ang",
  "Deg Hit'an",
  "Degar",
  "Delaware",
  "Dena'ina",
  "Dendi",
  "Derbish",
  "Desana",
  "Dhodia",
  "Didos",
  "Diegueno",
  "Dinka",
  "Diola",
  "Djerma Songhai",
  "Dogon",
  "Dolgan",
  "Dom",
  "Doma",
  "Dominican",
  "Don Cossack",
  "Dong",
  "Dongxiang",
  "Dorze",
  "Dravidian",
  "Drung",
  "Druze",
  "Du",
  "Duala",
  "Dutch",
  "Eastern Slav",
  "Ecuadorian",
  "Egyptian",
  "Elema",
  "Enets",
  "Enga",
  "English",
  "Enxet",
  "Eshira",
  "Eskimo",
  "Esselen",
  "Estonian",
  "Estonian",
  "Eurasian Avar",
  "Europe",
  "Even",
  "Evenki",
  "Ewe",
  "Falasha/Beta Israel",
  "Fante",
  "Faroese",
  "Fars",
  "Fereydan",
  "Fernandino",
  "Fijian",
  "Filipino",
  "Finn",
  "Finnish ",
  "Flemish",
  "Fon",
  "Fox",
  "Franco Mauritian",
  "Franco Réunionnaise",
  "Frank",
  "French",
  "Frisian",
  "Fula/Fulfulde",
  "Fulni o",
  "Fur",
  "Ga",
  "Gael",
  "Gagauz",
  "Galician",
  "Gaoshan",
  "Garifuna/Garinagu",
  "Ge",
  "Geba Buru",
  "Gelao",
  "Georgian",
  "German",
  "Gia Rai",
  "Giay",
  "Gie Trieng",
  "Gitano",
  "Godoberi",
  "Gogodali",
  "Gongduk",
  "Goral",
  "Gorani",
  "Goshute",
  "Goulaye",
  "Greek",
  "Griqua",
  "Gros Ventre",
  "Gruzinim",
  "Guadeloupean",
  "Guajajara",
  "Guarani",
  "Gujarati",
  "Gullah",
  "Gurage",
  "Guria",
  "Guru",
  "Guruk",
  "Gurung",
  "Guyanese",
  "H'Re",
  "Hadza",
  "Haida",
  "Haitian Creole",
  "Hakka",
  "Haliwa Saponi",
  "Hamer",
  "Hamsheni",
  "Han Chinese",
  "Hani",
  "Hausa",
  "Havasupai",
  "Haw",
  "Hawaiian",
  "Hazara",
  "Hebrew Israelite",
  "Herero",
  "Hesquiat",
  "Hezhen",
  "Hidatsa",
  "Himba",
  "Hindoestanen",
  "Hinukh",
  "Hispanic",
  "Hmar",
  "Hmong",
  "Hmong ",
  "Ho Chunk",
  "Hoa",
  "Hoh",
  "Hohokam",
  "Hoklo",
  "Holikachuk",
  "Hopi",
  "Houma",
  "Hualapai",
  "Huastec",
  "Hui Chinese",
  "Huicol",
  "Huli",
  "Hun",
  "Hungarian",
  "Hunzakut",
  "Hunzib",
  "Hupa",
  "Huron",
  "Hurrian",
  "Hutsul",
  "Hutu",
  "Hyksos",
  "I Kiribati",
  "Iatmul",
  "Iban",
  "Ibanag",
  "Ibibio",
  "Icelander",
  "Igbo",
  "Igorot",
  "Illiniwek/Illinois",
  "Ilocano",
  "Ilonggo",
  "Imereti",
  "Incan",
  "Ingessana",
  "Ingrian",
  "Ingushe",
  "Innu",
  "Inuit",
  "Irani",
  "Iranian",
  "Irish",
  "Irish ",
  "Irish Traveller",
  "Iroquois",
  "Ishkashmis",
  "Isleta",
  "Isoko",
  "Istriot",
  "Istro Romanian",
  "Italian",
  "Itelmen",
  "Itsekiri",
  "Izhorian",
  "Jakaltek",
  "Jakut",
  "Jamaican",
  "Janjevci",
  "Jat",
  "Javanese",
  "Jebala",
  "Jemez",
  "Jew",
  "Jing",
  "Jing",
  "Jingpo",
  "Jino",
  "Jivaro",
  "Jola",
  "Jopadhola",
  "Jri",
  "Kabardin",
  "Kabyle",
  "Kadiweu",
  "Kaibartta",
  "Kakheti",
  "Kalasha",
  "Kalenjin",
  "Kaliai",
  "Kalispel",
  "Kallawaya",
  "Kaluli",
  "Kamas",
  "Kamayura",
  "Kanembu",
  "Kapampangan",
  "Kapauku",
  "Karachay",
  "Karaims",
  "Karaja",
  "Karakalpak",
  "Karamanlides",
  "Karamojong",
  "Karatas",
  "Karelian",
  "Karen",
  "Karok",
  "Kashubian",
  "Katang",
  "Kato",
  "Katuquina",
  "Kavango",
  "Kaw",
  "Kayapo",
  "Kazakh",
  "Kenyah",
  "Kerek",
  "Keresan",
  "Kets",
  "Khakas",
  "Khang",
  "Khants",
  "Khazar",
  "Khevi",
  "Khevsureti",
  "Khinalug",
  "Khmer",
  "Khmer ",
  "Khmu",
  "Kho Mu",
  "Khoikhoi",
  "Khojas",
  "Khomani/Nu",
  "Khufi",
  "Khvarchi",
  "Kickapoo",
  "Kikuyu",
  "Kinh",
  "Kiowa",
  "Klallam",
  "Klamath",
  "Klikitat",
  "Kogi",
  "Kolchan",
  "Kombai",
  "Komi",
  "Kongo",
  "Koniag",
  "Kootenai",
  "Koptian",
  "Korean",
  "Korowai",
  "Koryaks",
  "Koskimo",
  "Kosraean",
  "Koyukon",
  "Kpelle",
  "Kraho",
  "Krashovan",
  "Kri",
  "Kryz",
  "Kuban Cossack",
  "Kubu",
  "Kuikuru",
  "Kumeyaay",
  "Kumyk",
  "Kuna",
  "Kurd",
  "Kuruba Gowda",
  "Kutenai",
  "Kwakiutl",
  "Kwakwaka'wakw",
  "Kyrgyz",
  "La Chi",
  "La Ha",
  "La Hu",
  "Laguna",
  "Lahu",
  "Laigain",
  "Lakota",
  "Laks",
  "Lamet",
  "Lao",
  "Lao ",
  "Lao Sung",
  "Lao Theung",
  "Latgalian",
  "Latino",
  "Latvian",
  "Lavae",
  "Laven",
  "Layap",
  "Laz",
  "Lazoi",
  "Lebanese ",
  "Lebou",
  "Lemkos",
  "Lenca",
  "Lengua",
  "Lezgi",
  "Lhoba",
  "Lhotshampa",
  "Li",
  "Liechtensteiner",
  "Limbus",
  "Lipka Tatar",
  "Lipovan",
  "Lisu",
  "Lithuanian",
  "Livonian",
  "Lo Lo",
  "Lobi",
  "Lotuko",
  "Louisiana Creole",
  "Lozi",
  "Lua",
  "Luba",
  "Lue",
  "Luiseno",
  "Lumad",
  "Lumbee",
  "Lummi",
  "Lunda",
  "Luo",
  "Lusitanian",
  "Luxembourger",
  "Métis",
  "M'Baka",
  "Maasai",
  "Macedo Romanian",
  "Macedonian",
  "Macuxi",
  "Madurese",
  "Magyar ",
  "Magyar Canadian",
  "Magyar/Hungarian",
  "Mahican",
  "Mahorian",
  "Maidu",
  "Mailu",
  "Maingtha",
  "Maka",
  "Makah",
  "Makong",
  "Makua",
  "Malagasi",
  "Malay",
  "Malayalee",
  "Malaysian",
  "Malinké",
  "Maliseet",
  "Maltese",
  "Mam",
  "Mamamwa",
  "Manasi",
  "Manchu",
  "Mandan",
  "Mandinka",
  "Mang",
  "Mangbetu",
  "Mangyan",
  "Mansis",
  "Manx",
  "Maonan",
  "Maori",
  "Mapuche",
  "Maratha",
  "Marathi",
  "Mari",
  "Maricopa",
  "Marind Anim",
  "Mashantucket Pequot",
  "Matabele",
  "Mataco",
  "Matis",
  "Mattaponi",
  "Maubere",
  "Maya",
  "Mayo",
  "Mazandareni",
  "Mbaya",
  "Mbochi",
  "Mbuti",
  "Mbuti",
  "Me Wuk",
  "Megleno Romanian",
  "Meherrin",
  "Mekeo",
  "Mekeo",
  "Melungeon",
  "Memon",
  "Menba",
  "Mende",
  "Menominee",
  "Mentawai",
  "Meskhetian",
  "Mexican",
  "Mi'kmaq",
  "Miao",
  "Miccosukee",
  "Mina",
  "Minahasa/Manadonese",
  "Minangkabau",
  "Mingo",
  "Mingrelian",
  "Miskito",
  "Mission",
  "Mitsogo",
  "Miwok",
  "Mixtec",
  "Miyakoan",
  "Mizo",
  "Mizrahim",
  "Mlabri",
  "Mnong",
  "Modoc",
  "Mohave",
  "Mohawk",
  "Mohegan",
  "Moldovan",
  "Molise Croat",
  "Mon",
  "Monacan",
  "Mongo",
  "Mongol",
  "Mono",
  "Montagnais",
  "Montaukett",
  "Montenegrin",
  "Moor",
  "Moravian",
  "Moriori",
  "Morisco",
  "Morlach",
  "Moro",
  "Mossi",
  "Motu",
  "Motu",
  "Muckleshoot",
  "Mudéjar",
  "Muhajir Pakistani",
  "Mulam",
  "Mulatto",
  "Munda",
  "Mundurucu",
  "Muong",
  "Mursi",
  "Museu",
  "Myene",
  "N/u or Khomani",
  "Naga",
  "Nahanni",
  "Nahua",
  "Namaqua",
  "Nanais",
  "Nansemond",
  "Narragansett",
  "Nasia",
  "Natchez",
  "Nauruan",
  "Navajo",
  "Naxi",
  "Ndau",
  "Negidal",
  "Negrito",
  "Nenet",
  "Nespelem",
  "Nevisian",
  "Newar",
  "Newfoundlander",
  "Nez Percé",
  "Ngac'ang",
  "Ngae",
  "Nganasan",
  "Ngasan",
  "Nhahuen",
  "Nhuon",
  "Ni Vanuatu",
  "Niominka",
  "Nipmuc",
  "Nishka",
  "Nisqually",
  "Niuean",
  "Nivkhs",
  "Njem",
  "Nogais",
  "Nomlaki",
  "Nooksack",
  "Norwegian",
  "Norwegian ",
  "Norwegian Canadian",
  "Nu",
  "Nuba",
  "Nubian",
  "Nuer",
  "Nukak",
  "Nung",
  "Nuu chah nulth",
  "Nyagatom",
  "Nzema",
  "O Du",
  "Odawa",
  "Ogaden",
  "Oglala",
  "Ogoni",
  "Ojibwa",
  "Okamba",
  "Okande",
  "Okinawan",
  "Omagua",
  "Omaha",
  "Oneida",
  "Onondaga",
  "Orochis",
  "Orokaiva",
  "Oroks",
  "Oromo",
  "Oroqin",
  "Oroshoris",
  "Osage",
  "Ossetian",
  "Otavaleño",
  "Otoe Missouria",
  "Ottawa",
  "Ovambo",
  "Pa O",
  "Pa Then",
  "Pa Thi",
  "Paiute",
  "Pakeha",
  "Pakoh",
  "Palcene",
  "Paliyan",
  "Pamunkey",
  "Pangasinense",
  "Panoan",
  "Parsi",
  "Pashtun",
  "Pashu",
  "Passamaquoddy",
  "Pataxo",
  "Paugusset",
  "Pawnee",
  "Penan",
  "Pennsylvania Dutch",
  "Pennsylvania German",
  "Penobscot",
  "Peoria",
  "Perce",
  "Persian",
  "Peruvian",
  "Petcheneg",
  "Phoenician",
  "Phong",
  "Phu La",
  "Phu Noi",
  "Phu Thai",
  "Pied noir",
  "Piegan",
  "Pilaga",
  "Pima",
  "Pit River Indian",
  "Pitcairn Norfolk",
  "Polabian Slav",
  "Polish",
  "Pomaks",
  "Pomo",
  "Ponca",
  "Ponhpeian",
  "Pontic Greek",
  "Poospatuck",
  "Portuguese",
  "Potawatomi",
  "Potiguara",
  "Powhatan",
  "Pu Peo",
  "Pueblo",
  "Puelche",
  "Puerto Rican",
  "Puget Sound Salish",
  "Pumi",
  "Punan",
  "Punjabi",
  "Purépecha",
  "Puyallup",
  "Q'eros",
  "Qashqai",
  "Qiang",
  "Quahatika",
  "Quapaw",
  "Quebecer",
  "Quechan",
  "Quechua",
  "Quiché",
  "Quileute",
  "Quinault",
  "Quinqui",
  "Ra Glai",
  "Rais",
  "Rakhine",
  "Rakuba",
  "Ramapough Mountain Indian",
  "Rappahannock",
  "Rashaida",
  "Ro Mam",
  "Rohingya",
  "Roma",
  "Romanian",
  "Roshanis",
  "Rotuman",
  "Russian",
  "Rusyn",
  "Ruthenian",
  "Rutul",
  "Ryukyuan",
  "S'Klallam",
  "Sadang",
  "Saek",
  "Saho",
  "Saingolo",
  "Salar",
  "Salish",
  "Samanthan",
  "Samaritan",
  "Samburu",
  "Samegrelo",
  "Sami",
  "Samoan",
  "Samogitian",
  "Samojeed",
  "Samtao",
  "San",
  "San Chay",
  "San Diu",
  "Sanema",
  "Santal",
  "Santee Sioux",
  "Saponi",
  "Sara",
  "Sarakatsani",
  "Saramaka",
  "Sauk",
  "Sauk Suiattle",
  "Saxon",
  "Scanger",
  "Scots Irish ",
  "Scottish",
  "Sekani",
  "Selk'nam",
  "Selkup",
  "Seminole",
  "Sena",
  "Seneca",
  "Sentinelese",
  "Sephardi",
  "Serb",
  "Serer",
  "Serer Ndut",
  "Seychellois Creole",
  "Shan",
  "Shangaan",
  "Shasta",
  "Shavante",
  "Shawnee",
  "She",
  "Sherpa",
  "Shinnecock",
  "Shipibo",
  "Shoalwater Bay Tribe",
  "Shona",
  "Shor",
  "Shoshone",
  "Shughnis",
  "Shui",
  "Si La",
  "Sidamo",
  "Siddi",
  "Siksika",
  "Silesian",
  "Siletz",
  "Sindhis",
  "Singmun",
  "Sinhala",
  "Sinti",
  "Sioux",
  "Siuslaw",
  "Skagit",
  "Skokomish",
  "Slav",
  "Slovak",
  "Slovene",
  "Sokci",
  "Somali",
  "Somba",
  "Songhai",
  "Sorb",
  "Soso",
  "Souei",
  "Southern Tutchone",
  "Spanish",
  "Spokane",
  "Squamish/Skwxwú7mesh",
  "Squaxin Island Tribe",
  "Sri Lankan",
  "Sri Lankan Moor",
  "Stillaguamish",
  "Sudanese Australian",
  "Sundanese",
  "Suquamish",
  "Suri",
  "Surui",
  "Susu",
  "Suyá",
  "Svan",
  "Swahili",
  "Swazi",
  "Swede",
  "Swinomish",
  "Ta Oi",
  "Tabasaran",
  "Tache",
  "Tachi",
  "Tagalog",
  "Tagish",
  "Taiwanese aborigine",
  "Tajik",
  "Taliang",
  "Talysh",
  "Tamang",
  "Tamil",
  "Tanana",
  "Tanna",
  "Taos",
  "Tapajo",
  "Tapirapé",
  "Tapuia",
  "Tarahumara",
  "Tarascan",
  "Tasaday",
  "Tatar",
  "Tatar",
  "Tats",
  "Tay",
  "Taíno",
  "Teda",
  "Tehuelche",
  "Teimani Jewish",
  "Tejano",
  "Telefolmin",
  "Terena",
  "Teton",
  "Tewa",
  "Thai",
  "Thai-Lue",
  "Tharu",
  "Thin",
  "Tho",
  "Tibetan",
  "Ticuna",
  "Tigray",
  "Tigray Tigrinia",
  "Tigre",
  "Tigrinya",
  "Tigua",
  "Tindis",
  "Tlakluit",
  "Tlingit",
  "Toala",
  "Toba",
  "Tocharian",
  "Tofalar",
  "Tohono O'odham",
  "Tokelauan",
  "Tolais",
  "Tolowa",
  "Toltec",
  "Tongan",
  "Tongva",
  "Tonkawa",
  "Topachula",
  "Toraja",
  "Torbesh",
  "Torres Strait Islander",
  "Totonac",
  "Toubou",
  "Transylvanian Saxon",
  "Traveller",
  "Trinidadian",
  "Trinidadian",
  "Trukhmen",
  "Tsakhur",
  "Tsetsaut",
  "Tsimishian",
  "Tsonga",
  "Tsuu T'ina",
  "Tswana",
  "Tuamotu",
  "Tuareg",
  "Tujia",
  "Tukano",
  "Tukolor",
  "Tulalip",
  "Tulutni",
  "Tum",
  "Tumbuka",
  "Tungus",
  "Tunica Biloxi",
  "Tupian",
  "Tupinamba",
  "Turkish",
  "Turkish Cypriot",
  "Tusheti",
  "Tutsi",
  "Tuvaluan",
  "Tuvan",
  "Twa",
  "Txicao",
  "Tzigane",
  "U'wa",
  "Ubykh",
  "Udeghes",
  "Udis",
  "Ukrainian",
  "Ulchs",
  "Ulster Scots",
  "Ulta",
  "Umatilla",
  "Umpqua",
  "Upper Skagit",
  "Uruguayan",
  "Ute",
  "Uyghur",
  "Uzbek",
  "Vaccaei",
  "Vandal",
  "Vaturanga",
  "Venda",
  "Veps",
  "Vietnamese ",
  "Visayan",
  "Vlach",
  "Volga German",
  "Votes",
  "Wa",
  "Wabanaki",
  "Waccamaw",
  "Wailaki",
  "Waitaha",
  "Waiwai",
  "Wakh",
  "Waki",
  "Walla Walla",
  "Wampanoag",
  "Wasco",
  "Washoe",
  "Wayana",
  "Welayta",
  "Welsh",
  "Wend",
  "White Mountain Apache",
  "Wichita",
  "Wintun",
  "Wiyot",
  "Wolof",
  "Wyandot",
  "Wyyanaha",
  "Xacriaba",
  "Xavante",
  "Xerente",
  "Xhosa",
  "Xibe",
  "Xikrin",
  "Xinh Mun",
  "Xo Dang",
  "Xtieng",
  "Xucuru",
  "Xueda",
  "Yae",
  "Yaeyaman",
  "Yaghan",
  "Yaghnabis",
  "Yagua",
  "Yakama",
  "Yakughir",
  "Yakut",
  "Yamato",
  "Yang",
  "Yankton Sioux",
  "Yanomami",
  "Yao",
  "Yapese",
  "Yaqui",
  "Yavapai",
  "Yawalpiti",
  "Yawanawa",
  "Yazgulami",
  "Yekuana",
  "Yi",
  "Yocha Dehe",
  "Yokut",
  "Yonagunian",
  "Yoruba",
  "Yuchi",
  "Yugur",
  "Yukaghir",
  "Yuki",
  "Yuma",
  "Yumbri",
  "Yupik",
  "Yurok",
  "Yurok",
  "Yörük",
  "Zaghawa",
  "Zapotec",
  "Zazas",
  "Zeibek",
  "Zhuang",
  "Zou",
  "Zulian",
  "Zulu",
  "Zuni"
];
var usages = [
  "with friends",
  "at work",
  "at school",
  "for social events",
  "when alone",
  "in private",
  "at home"
];
var types = [
  "woman",
  "trans woman",
  "man",
  "trans man",
  "nobinary person"
];
var fluencys = [
  "natively",
  "fluently",
  "conversationally",
  "almost conversationally",
  "enough to get by",
  "as a student"
];
var languages = [
  "!Kung",
  "!Xoo",
  "Abanyom",
  "Abaza",
  "Abenaki",
  "Abkhaz",
  "Abujmaria",
  "Acehnese",
  "Adamorobe Sign",
  "Adele",
  "Adyghe",
  "Afar",
  "Afrikaans",
  "Afro-Seminole Creole",
  "Aimaq",
  "Aini",
  "Ainu",
  "Akan",
  "Akawaio",
  "Aklanon",
  "Albanian",
  "Alemán Coloneiro",
  "Aleut",
  "Algonquin",
  "Alsatian",
  "Altay",
  "Alutor",
  "Amdang",
  "American Sign",
  "Amharic",
  "Andalusian",
  "Angaur",
  "Angika",
  "Anglo-Saxon",
  "Anyin",
  "Ao",
  "A-Pucikwar",
  "Arabic",
  "Aragonese",
  "Aramaic",
  "Are",
  "Argobba",
  "Armenian",
  "Aromanian",
  "Arvanitic",
  "Ashkenazi Hebrew",
  "Ashkun",
  "Asi",
  "Assamese",
  "Assyrian Neo-Aramaic",
  "Asturian",
  "Ateso",
  "Ati",
  "Auslan",
  "Avar",
  "Avestan",
  "Awadhi",
  "Aymara",
  "Azerbaijani",
  "Badaga",
  "Badeshi",
  "Bahnar",
  "Bajelani",
  "Balinese",
  "Balochi",
  "Balti",
  "Bambara",
  "Banjar",
  "Banyumasan",
  "Basaa",
  "Bashkir",
  "Basque",
  "Batak Dairi",
  "Batak Karo",
  "Batak Mandailing",
  "Batak Simalungun",
  "Batak Toba",
  "Bateri",
  "Bats",
  "Bavarian",
  "Beja",
  "Belarusian",
  "Belhare",
  "Bellari",
  "Bemba",
  "Bengali",
  "Bengali Sign",
  "Berber",
  "Berta",
  "Bete",
  "Bété",
  "Bezhta",
  "Bhili",
  "Bhojpuri",
  "Bijil Neo-Aramaic",
  "Bikol",
  "Bikya",
  "Bissa",
  "Blackfoot",
  "Boholano",
  "Bohtan Neo-Aramaic",
  "Bonan",
  "Bororo",
  "Bosnian",
  "Brahui",
  "Breton",
  "British Sign",
  "Bua",
  "Buginese",
  "Bukusu",
  "Bulgarian",
  "Bunjevac",
  "Burmese",
  "Burushaski",
  "Buryat",
  "Caluyanon",
  "Cantonese",
  "Catalan",
  "Cayuga",
  "Cebuano",
  "Chabacano",
  "Chaga",
  "Chaldean",
  "Chamorro",
  "Chaouia",
  "Chechen",
  "Chenchu",
  "Chenoua",
  "Cherokee",
  "Cheyenne",
  "Chhattisgarhi",
  "Chichewa",
  "Chilcotin",
  "Chinese",
  "Chintang",
  "Chipewyan",
  "Chiricahua",
  "Chittagonian",
  "Choctaw",
  "Chorasmian",
  "Chukchi",
  "Chulym",
  "Church Slavonic",
  "Chuukese",
  "Chuvash",
  "Cocoma",
  "Cocopa",
  "Coeur d'Alene",
  "Comorian",
  "Cornish",
  "Corsican",
  "Cree",
  "Crimean Tatar",
  "Croatian",
  "Cuyonon",
  "Czech",
  "Dahlik",
  "Dalecarlian",
  "Dameli",
  "Danish",
  "Dargin",
  "Dari",
  "Dari-Persian",
  "Darkhat",
  "Daur",
  "Dena'ina",
  "Dhatki",
  "Dhivehi",
  "Dida",
  "Dioula",
  "Dogri",
  "Dogrib",
  "Dolgan",
  "Domaaki",
  "Dongxiang",
  "Duala",
  "Dungan",
  "Dutch",
  "Dzhidi",
  "Dzongkha",
  "Eastern Yugur",
  "Egyptian Arabic",
  "Ekoti",
  "Endegen",
  "Enets",
  "English",
  "Ennemor",
  "Erzya",
  "Esperanto",
  "Estonian",
  "Even",
  "Evenk",
  "Ewe",
  "Eyak",
  "Faeroese",
  "Fang",
  "Fars",
  "Fijian",
  "Filipino",
  "Finnish",
  "Finnish Sign",
  "Fon",
  "Franco-Provençal",
  "French",
  "French Sign",
  "Frisian, North",
  "Frisian, Saterland",
  "Frisian, West",
  "Friulian",
  "Fula",
  "Fur",
  "Ga",
  "Gadaba",
  "Gagauz",
  "Galician",
  "Gan",
  "Gangte",
  "Garhwali",
  "Gawar-Bati",
  "Gayo",
  "Gazi",
  "Gen",
  "Georgian",
  "German",
  "German Sign",
  "Gikuyu",
  "Gilbertese",
  "Gileki",
  "Goaria",
  "Gondi",
  "Grangali",
  "Greek",
  "Guaraní",
  "Gujarati",
  "Gula Iro",
  "Gullah",
  "Gusii",
  "Gwich'in",
  "Hadza",
  "Haida",
  "Haitian Creole",
  "Hakka",
  "Hän",
  "Harari",
  "Harauti",
  "Harsusi",
  "Harzani",
  "Hausa",
  "Havasupai",
  "Hawaii Pidgin Sign",
  "Hawaiian",
  "Hazaragi",
  "Hebrew",
  "Herero",
  "Hértevin",
  "Hiligaynon",
  "Hindi",
  "Hinukh",
  "Hiri Motu",
  "Hittite",
  "Hixkaryana",
  "Hmong",
  "Ho",
  "Hobyót",
  "Hopi",
  "Hulaulá",
  "Hungarian",
  "Hutterite German",
  "Iban",
  "Ibanag",
  "Ibibio",
  "Icelandic",
  "Igbo",
  "Ikalanga",
  "Ili Turki",
  "Ilokano",
  "Inari Sami",
  "Indonesian",
  "Ingrian",
  "Ingush",
  "Inuktitut",
  "Inupiaq",
  "Inuvialuktun",
  "Iraqw",
  "Irish",
  "Irish Sign",
  "Irula",
  "Isan",
  "Istro-Romanian",
  "Italian",
  "Itelmen",
  "Jacaltec",
  "Jalaa",
  "Japanese",
  "Jaqaru",
  "Jarai",
  "Javanese",
  "Jibbali",
  "Jicarilla Apache",
  "Juang",
  "Kabardian",
  "Kabyle",
  "Kachin",
  "Kalaallisut",
  "Kalami",
  "Kalasha",
  "Kalmyk",
  "Kankanai",
  "Kannada",
  "Kaonde",
  "Kapampangan",
  "Karachay-Balkar",
  "Karagas",
  "Karaim",
  "Karakalpak",
  "Karelian",
  "Kashmiri",
  "Kashubian",
  "Kazakh",
  "Kensiu",
  "Kerek",
  "Ket",
  "Khakas",
  "Khalaj",
  "Kham",
  "Khandeshi",
  "Khanty",
  "Khasi",
  "Khirwar",
  "Khmer",
  "Khmu",
  "Khowar",
  "Khunsari",
  "Kildin Sami",
  "Kimatuumbi",
  "Kinaray-a",
  "Kinyarwanda",
  "Kirombo",
  "Kirundi",
  "Kivunjo",
  "Klallam",
  "Kodava Takk",
  "Kohistani",
  "Kolami",
  "Komi",
  "Konda",
  "Kongo",
  "Konkani",
  "Koraga",
  "Korandje",
  "Korean",
  "Korku",
  "Korowai",
  "Korwa",
  "Koryak",
  "Kosraean",
  "Kota",
  "Koy Sanjaq Surat",
  "Koya",
  "Koyra Chiini",
  "Krymchak",
  "Kui",
  "Kujarge",
  "Kumauni",
  "Kumyk",
  "Kumzari",
  "Kurdish",
  "Kurukh",
  "Kurumba",
  "Kuvi",
  "Kwanyama",
  "Kxoe",
  "Kyrgyz",
  "Laal",
  "Ladakhi",
  "Ladin",
  "Ladino",
  "Lakota",
  "Lambadi",
  "Lao",
  "Latin",
  "Latvian",
  "Laz",
  "Leonese",
  "Lezgi",
  "Ligbi",
  "Lingala",
  "Lipan Apache",
  "Lisan al-Dawat",
  "Lishana Deni",
  "Lishanid Noshan",
  "Lithuanian",
  "Livonian",
  "Lombard",
  "Lotha",
  "Low German",
  "Lower Sorbian",
  "Lozi",
  "Ludic",
  "Luganda",
  "Lunda",
  "Luri",
  "Lushootseed",
  "Lusoga",
  "Luvale",
  "Luwati",
  "Luxembourgish",
  "Macedonian",
  "Magadhi",
  "Maguindanao",
  "Mahl",
  "Maithili",
  "Makasar",
  "Makhuwa",
  "Makhuwa-Meetto",
  "Malagasy",
  "Malay",
  "Malayalam",
  "Malaysian Sign",
  "Maltese",
  "Malto",
  "Malvi",
  "Mam",
  "Manchurian",
  "Manda",
  "Mandaic",
  "Mandarin",
  "Mandinka",
  "Mansi",
  "Manyika",
  "Maori",
  "Mapudungun",
  "Maragoli",
  "Maranao",
  "Marathi",
  "Mari",
  "Maria",
  "Marquesan",
  "Marshallese",
  "Martha's Vineyard Sign",
  "Masaba",
  "Masbatenyo",
  "Mauritian Creole",
  "Maya",
  "Mazandarani",
  "Meänkieli",
  "Megleno-Romanian",
  "Megrelian",
  "Mehri",
  "Meitei",
  "Menominee",
  "Mentawai",
  "Meru",
  "Mescalero Apache",
  "Mesqan",
  "Michif",
  "Mikasuki",
  "Mi'kmaq",
  "Minangkabau",
  "Mirandese",
  "Mobilian Jargon",
  "Moghol",
  "Mohawk",
  "Moksha",
  "Molengue",
  "Mon",
  "Mongolian",
  "Mono",
  "Mono",
  "Mono",
  "Montagnais",
  "Montenegrin",
  "Motu",
  "Muher",
  "Mundari",
  "Munji",
  "Murcian",
  "Muria",
  "Murut",
  "N_u",
  "Nafaanra",
  "Nagarchal",
  "Nahuatl",
  "Naiki",
  "Nama",
  "Nanai",
  "Natanzi",
  "Nauruan",
  "Navajo",
  "Nayini",
  "Ndau",
  "Ndebele",
  "Ndonga",
  "Neapolitan",
  "Negidal",
  "Nenets",
  "Nepal Bhasa",
  "Nepali",
  "New Zealand Sign",
  "Nganasan",
  "Ngumba",
  "Nheengatu",
  "Nicaraguan Sign",
  "Niellim",
  "Nigerian Pidgin",
  "Niuean",
  "Nivkh",
  "Nogai",
  "Pitcairn-Norfolk",
  "Norman",
  "Northern Sami",
  "Northern Sotho",
  "Northern Straits Salish)",
  "Northern Yukaghir",
  "Norwegian",
  "Nuer",
  "Nuxálk",
  "Nyabwa",
  "Nyah Kur",
  "Nyangumarta",
  "Nyoro",
  "Occitan",
  "Ojibwe",
  "Olonets Karelian",
  "Omagua",
  "Ongota",
  "Oriya",
  "Ormuri",
  "Oroch",
  "Orok",
  "Oromo",
  "Ossetic",
  "Palauan",
  "Pangasinan",
  "Papiamento",
  "Parachi",
  "Parauk",
  "Parji",
  "Parya",
  "Pashto",
  "Passamaquoddy",
  "Pemon",
  "Pengo",
  "Pennacook",
  "Pennsylvania Dutch",
  "Persian",
  "Phalura",
  "Phuthi",
  "Picard",
  "Pirahã",
  "Plautdietsch",
  "Polish",
  "Portuguese",
  "Pothohari",
  "Pradhan",
  "Provençal",
  "Puelche",
  "Puma",
  "Punjabi",
  "Qashqai",
  "Quebec Sign",
  "Quechua",
  "Rajasthani",
  "Ratagnon",
  "Réunion Creole",
  "Romanian",
  "Romansh",
  "Romany",
  "Romblomanon",
  "Rotokas",
  "Runyankole",
  "Russian",
  "Russian Sign",
  "Ruthenian",
  "Salar",
  "Samoan",
  "Sandawe",
  "Sangisari",
  "Sanglechi-Ishkashimi",
  "Sango",
  "Sanskrit",
  "Santali",
  "Sara",
  "Saramaccan",
  "Sardinian",
  "Sarikoli",
  "Saurashtra",
  "Savara",
  "Savi",
  "Sawai",
  "Scots",
  "Scottish Gaelic",
  "Selangor Sign",
  "Selkup",
  "Semnani",
  "Senaya",
  "Sephardi Hebrew",
  "Serbian",
  "Serbo-Croatian",
  "Sesotho",
  "Seto",
  "Seychellois Creole",
  "Shahrudi",
  "Shimaore",
  "Shina",
  "Shona",
  "Shor",
  "Shughni",
  "Shumashti",
  "Shuswap",
  "Sicilian",
  "Sidamo",
  "Sika",
  "Silesian",
  "Silt'e",
  "Sindhi",
  "Sinhalese",
  "Sioux",
  "Siraiki",
  "Sivandi",
  "Skolt Sami",
  "Slavey",
  "Slovak",
  "Slovene",
  "Soddo",
  "Soi",
  "Somali",
  "Sonjo",
  "Sonsorolese",
  "Soqotri",
  "Sora",
  "Sorbian, Lower",
  "Sorbian, Upper",
  "Sourashtra",
  "South Estonian",
  "Southern Sami",
  "Southern Yukaghir",
  "Spanish",
  "Sranan Tongo",
  "St'at'imcets",
  "Suba",
  "Sucite",
  "Sundanese",
  "Supyire",
  "Surigaonon",
  "Susu",
  "Svan",
  "Swahili",
  "Swati",
  "Swedish",
  "Syriac",
  "Tabasaran",
  "Tachelhit",
  "Tagalog",
  "Tahitian",
  "Taiwanese Sign",
  "Tajik",
  "Takestani",
  "Talysh",
  "Tamil",
  "Tanacross",
  "Tarifit",
  "Tat",
  "Tatar",
  "Tausug",
  "Tehuelche",
  "Telugu",
  "Temiar",
  "Tepehua",
  "Tepehuán",
  "Tetum",
  "Thai",
  "Tharu",
  "Tibetan",
  "Tigre",
  "Tigrinya",
  "Tirahi",
  "Tiv",
  "Tlingit",
  "Tobian",
  "Toda",
  "Tok Pisin",
  "Tokelauan",
  "Tonga",
  "Tongan",
  "Torwali",
  "Tregami",
  "Tsat",
  "Tsez",
  "Tshiluba",
  "Tsimshian",
  "Tsonga",
  "Tswana",
  "Tu",
  "Tuaregs",
  "Tulu",
  "Tumbuka",
  "Tupiniquim",
  "Turkish",
  "Turkmen",
  "Turoyo",
  "Tuvaluan",
  "Tuvan Tuvin",
  "Udihe",
  "Udmurt",
  "Ukrainian",
  "Ulbare",
  "Ulch",
  "Unserdeutsch",
  "Upper Sorbian",
  "Urdu",
  "Uripiv",
  "Urum",
  "Ute",
  "Uyghur",
  "Uzbek",
  "Vafsi",
  "Valencian",
  "Valencian Sign",
  "Vasi-vari",
  "Venda",
  "Venetian",
  "Veps",
  "Vietnamese",
  "Võro",
  "Votic",
  "Waddar",
  "Waigali",
  "Waima",
  "Wakhi",
  "Walloon",
  "Waneci",
  "Wapishana",
  "Waray-Waray",
  "Washo",
  "Welsh",
  "Wolane",
  "Wolof",
  "Wotapuri-Katarqalai",
  "Wu",
  "Xhosa",
  "Xiang",
  "Xibe",
  "Xipaya",
  "Yaaku",
  "Yaeyama",
  "Yakut",
  "Yankunytjatjara",
  "Yanomami",
  "Yanyuwa",
  "Yapese",
  "Yaqui",
  "Yauma",
  "Yavapai",
  "Yazdi",
  "Yemenite Hebrew",
  "Yeni",
  "Yevanic",
  "Yi",
  "Yiddish",
  "Yogur",
  "Yokutsans",
  "Yonaguni",
  "Yorùbá",
  "Yucatec Maya",
  "Yuchi",
  "Yugur",
  "Yukaghirs",
  "Yupik",
  "Yurats",
  "Yurok",
  "Záparo",
  "Zapotec",
  "Zazaki",
  "Zhuang",
  "Zoque",
  "Zulu",
  "Zuñi",
  "Zway",
  "Zulu",
  "Zuñi",
  "Zway"
];
var approachs = [
  "hates to",
  "dislikes to",
  "feel obligated to",
  "likes to",
  "loves to"
];
var langskill = [
  'speaks',
  'reads and writes',
  'knows'
]
var instruments = [
  'abïa drum',
  'accordion',
  'agidigbo',
  'ajaeng',
  'alboka',
  'archlute',
  'arghul',
  'array mbira',
  'baglama',
  'bagpipes',
  'balalaika',
  'bandoneón',
  'banjo',
  'bansuri',
  'barbat',
  'bawu',
  'bayan',
  'biwa',
  'bodhrán',
  'cello',
  'charango',
  'chenda',
  'cimbasso',
  'cittern',
  'comb',
  'concertina',
  'contrabass á anche',
  'cromorne',
  'crotales',
  'dabakan',
  'ðàn nguyet',
  'ðàn tam thap luc',
  'ðàn tranh',
  'danso',
  'dholak',
  'dihu',
  'dizi',
  'djembe',
  'domra',
  'dvojnice',
  'ektara',
  'erhu',
  'erxian',
  'fangxiang',
  'fegereng',
  'flageolet',
  'flute',
  'french horn',
  'fujara',
  'gamelan',
  'gandingan',
  'gandingan a kayo',
  'ganzá',
  'gayageum',
  'gehu',
  'gemshorn',
  'gottuvadhyam',
  'guban',
  'guqin',
  'gusli',
  'hammered dulcimer',
  'hardanger fiddle',
  'hardart',
  'harmonica',
  'harp',
  'hegelong',
  'hocchiku',
  'horagai',
  'hosho',
  'huluhu',
  'hun',
  'huqin',
  'igil',
  'inci',
  'ipu',
  'janggu',
  'jiaohu',
  'kalimba',
  'katzenklavier',
  'kaval',
  'kendang',
  'keytar',
  'khene',
  'khim',
  'khlui',
  'kokyu',
  'koto',
  'kudyapi',
  'kulintang',
  'lambeg drums',
  'laruan',
  'leiqin',
  'likembe',
  'lirone',
  'luntang',
  'lusheng',
  'lute',
  'lyre',
  'maadal',
  'mandolin',
  'marimba',
  'mbira',
  'mijwiz',
  'mohan veena',
  'morin khuur',
  'morsing',
  'mridangam',
  'nadaswaram',
  'naqara',
  'ney',
  'nohkan',
  'nyckelharpa',
  'oboe',
  'ondes martenot',
  'ophicleide',
  'oud',
  'pasiyak',
  'piano',
  'pibgorn',
  'pipa',
  'pulalu',
  'quatro',
  'quatro',
  'quena',
  'quinticlave',
  'rackett',
  'rebab',
  'recorder',
  'riq',
  'ruan',
  'rudra vina',
  'ryuteki',
  'sabar',
  'sanshin',
  'saung',
  'saw sam sai',
  'saxophone',
  'setar',
  'shakuhachi',
  'shekere',
  'shishi odoshi',
  'shofar',
  'shvi',
  'sitar',
  'taiko',
  'tamburitza',
  'tan-tan',
  'thavil',
  'theorbo',
  'trumpet',
  'trychel',
  'tumpong',
  'udu',
  'ukulele',
  'valiha',
  'veena',
  'vichitra vina',
  'vielle',
  'vihuela',
  'viola',
  'violin',
  'washint',
  'willow flute',
  'xalam',
  'xiao',
  'xun',
  'yaylı tanbur',
  'yazheng',
  'yu',
  'zhonghu',
  'zhuihu',
  'zil',
  'zither',
  'zufoloz'
];
var coresidents = [
  "lover",
  "partner",
  "housemate",
  "offspring",
  "sibling",
  "employee",
  "older relative",
  "younger relative"
];
var pets = [
  "dog",
  "cat",
  "bird",
  "snake",
  "lizard"
];
var lifes = [
  "apartment",
  "houseboat",
  "motor home",
  "truck",
  "room",
  "house",
  "penthouse",
  "shelter",
  "squat",
  "tent",
  "townhouse",
  "trailer",
  "loft",
  "attic",
  "basement",
  "condo",
  "cabin",
  "hut"
];
var interiors = [
  "a cluttered",
  "a cozy",
  "a crammed",
  "a dirty",
  "a spotless",
  "a renovated",
  "a littered",
  "a chaotic",
  "an over-decorated",
  "a disorganized",
  "a spacious",
  "a cramped",
  "a vintage",
  "a minimalist",
  "an organized",
  "a rundown",
  "a bare",
  "a spartan"
];
var studies = [
  'Humanities',
  'Business Management',
  'Nursing',
  'Biology',
  'Psychology',
  'Medical Technnology',
  'Criminal Justice',
  'Education',
  'Engineering',
  'Finance',
  'Accounting',
  'Communications',
  'Journalism',
  'Dance',
  'Music',
  'Mechanics',
  'Computer Science',
  'Rehabilitation Therapy',
  'Physical Therapy',
  'English',
  'Economics',
  'Business Administration',
  'Computer Science',
  'Astronomy',
  'Information Technology',
  'History',
  'Political Science',
  'Design',
  'Visual Arts',
  'Earth Sciences',
  'Environmental Sciences',
  'Culinary Arts',
  'Food Service',
  'Civil Engineering',
  'Chemical Engineering',
  'Mechanical Engineering',
  'Audio Engineering',
  'Mathematics',
  'Dentistry',
  'Foreign Languages',
  'Linguistics',
  'Film',
  'Video',
  'Photography',
  'Comparative Religions',
  'Theology',
  'Protective Services',
  'International Relations',
  'Veterinary Studies',
  'Performing Arts',
  'Chemistry',
  'Law',
  'Food and Nutrition',
  'Pharmacy',
  'Physics',
  'Anthropology',
  'Archaeology',
  'Music',
  'Architecture',
  'Philosophy',
  'Agricultural Sciences',
  'Arts Management'
];
var educations = [
  "no plans to continue",
  "plans to continue",
  "is currently a full-time student",
  "is currently on hiatus",
  "is currently studying part-time"
];
var schoolings = [
  "a high school-level",
  "an associates-level",
  "a bachelors-level",
  "masters-level",
  "a doctoratal-level",
  "a fully self-taught",
  "a home-schooled"
];
var familytypes = [
  "a close-knit",
  "an abusive",
  "an emotionally-distant",
  "a small",
  "a large",
  "a loving",
  "a quiet",
  "an isolated",
  "a socially-isolated",
  "a gregarious",
  "an open",
  "an unconventional",
  "a conservative"
];
var religstrengths = [
  "lapsed",
  "casually",
  "culturally",
  "devout",
  "fanatical"
];
var socioeconomics = [
  "titled upper class",
  "nouveau riche",
  "upper class",
  "upper-middle class",
  "middle class",
  "lower-middle class",
  "working class",
  "poor"
];
var politics = [
  "Apolitical",
  "Agrarian",
  "Anarchist",
  "Aristocrat",
  "Authoritarian",
  "Autocrat",
  "China Democratic",
  "Communist",
  "Conservative",
  "Constitutionalist",
  "Danish Social Liberal",
  "Democrat",
  "Federalist",
  "Green Party",
  "Labour",
  "Left",
  "Left-Green",
  "Leninist",
  "Liberal Reform",
  "Libertarian Communist",
  "Maoist",
  "Marxist",
  "Monarchist",
  "Nationalist",
  "Neo-conservative",
  "Oligarch",
  "Paleolibertarian",
  "Plutocrat",
  "Progressive",
  "Pure Capitalist",
  "Radical Democrat",
  "Red-Green",
  "Reform",
  "Republican",
  "Revolutionary",
  "Social Christian",
  "Social Democrat",
  "Social Liberal",
  "Social Renewal",
  "Socialist",
  "Socialist Alternative",
  "Theocrat",
  "Tory",
  "Totalitarian",
  "Tribal",
  "Trotskyist",
  "Unionist",
  "Whig"
];
var gradestandings = [
  "beginner",
  "intermediate",
  "advanced",
  "expert"
];
var religions = [
  "Atheist",
  "Amish",
  "Anagon",
  "Anglican Catholic",
  "Apache",
  "Assyrian Catholic",
  "Ayyavazhi",
  "Bábist",
  "Baha'i",
  "Baptist",
  "Batuque",
  "Byzantine Catholic",
  "Candomblé",
  "Cao Dai",
  "Ch'ondogyo",
  "Christian Scientist",
  "Christian Spiritualist",
  "Confucianist",
  "Congregationalist",
  "Crow",
  "Dakota",
  "Eastern Orthodox Catholic",
  "Episcopalian",
  "Falun Gong",
  "Finnish",
  "Ghulat Muslim",
  "Gnostic",
  "Hasidic Jewish",
  "Hinayana Buddhist",
  "Hopi",
  "Jewish",
  "Inuit",
  "Jain",
  "Javanese Hindu",
  "Jehovah's Witness",
  "Khalam Muslim",
  "Kharijite Muslim",
  "Kumina",
  "Lakota",
  "Latin Rite Catholic",
  "Liberal Quaker",
  "Lingayata Hindu",
  "Lutheran",
  "Macumba",
  "Mahayana Buddhist",
  "Mami Wata",
  "Mandean Gnostic",
  "Manichaeist",
  "Mazdakism",
  "Mennonite",
  "Methodist",
  "Modern Orthodox Jewish",
  "Mormon",
  "Native Amer. Prostestant",
  "Navajo",
  "Neo-Pagan",
  "New Age",
  "Obeah",
  "Oriental Orthodox Catholic",
  "Orthodox Jewish",
  "Oyotunji",
  "Pentecostal",
  "Presbyterian",
  "Puritan",
  "Quaker",
  "Quimbanda",
  "Rastafarian",
  "Reform Jewish",
  "Roman Catholic",
  "Sabian",
  "Samaritan",
  "Santeria",
  "Seicho-No-Ie",
  "Seid Saami",
  "Seventh Day Adventist",
  "Shaiva Hindu",
  "Shakta Hindu",
  "Shi'a Muslim",
  "Shinto",
  "Sikh",
  "Smarta Hindu",
  "Sufi Muslim",
  "Sunni Muslim",
  "Tantric Hindu",
  "Taoist",
  "Tenrikyo",
  "Theravada Buddhist",
  "Umbanda",
  "Unitarian Universalist",
  "Vaastu Shastra Hindu",
  "Vaishnava Hindu",
  "Vajrayana Buddhist",
  "Vodoun",
  "Wonbulgyo",
  "Yazdânism",
  "Yiguandao",
  "Zen Buddhist",
  "Zoroastrian",
  "Zuni"
];
var works = [
  "full-time employee",
  "part-time employee",
  "remote employee",
  "temporary full-time employee",
  "temporary part-time employee",
  "irregularly employed",
  "self-employed",
  "independently wealthy thanks to investments in"
];
var industrys = [
  "Agriculture & Forestry Sector",
  "Animal Production",
  "Aquaculture ",
  "Cattle Ranching",
  "Hog and Pig Farming",
  "Commercial Fishing",
  "Crop Production",
  "Fruit & Tree Nut Farming",
  "Grain Farming",
  "Oilseed Farming",
  "Vegetable and Melon Farming",
  "Farm Support",
  "Nursery & Floriculture Production",
  "Timber Operations",
  "Arts, Entertainment & Recreation Sector",
  "Amusement Parks & Arcades",
  "Bowling Centers",
  "Fitness Centers",
  "Gambling",
  "Golf Courses",
  "Marinas",
  "Museums, Zoos & Parks",
  "Performing Arts Companies",
  "Professional Sports",
  "Ski Facilities",
  "Spa",
  "Talent & Modeling Agencies",
  "Business Services Sector",
  "Armored Vehicle",
  "Business Service Centers & Copy Shops",
  "Collection Agencies",
  "Credit Reporting & Collections",
  "Credit Reporting",
  "Exterminating & Pest Control",
  "Janitorial & Carpet Cleaning",
  "Landscaping",
  "Security Guard",
  "Security System",
  "Staffing",
  "Executive Search",
  "Professional Employer Organizations",
  "Surveillance, Investigation & Security Consulting",
  "Telephone Call Centers",
  "Trade Show & Event Planning",
  "Travel Agencies &",
  "Waste Management",
  "Hazardous Waste",
  "Remediation & Environmental Cleanup",
  "Solid Waste Services & Recycling",
  "Construction Sector",
  "Commercial & Heavy Construction",
  "Highway, Street, & Bridge Construction",
  "Power Line & Telecommunications Infrastructure Construction",
  "Residential Construction",
  "Residential Real Estate Development",
  "Specialty",
  "Concrete & Masonry",
  "Drywall, Plaster, Acoustic & Insulation",
  "Electrical",
  "Framing",
  "Painting & Wall Covering",
  "Plumbing & HVAC",
  "Roofing, Siding, & Sheet Metal",
  "Site Preparation",
  "Consumer",
  "Automotive Repair & Maintenance",
  "Automotive Oil Change & Lubrication",
  "Car Washes",
  "Electronic Equipment Repair",
  "Funeral",
  "Hair Care",
  "Laundry Facilities & Dry Cleaning",
  "Linen & Uniform Supply",
  "Parking Lots & Garages",
  "Weight Reduction",
  "Education Sector",
  "Colleges & Universities",
  "Community Colleges",
  "Education & Training",
  "Private Schools K-12",
  "Public Schools K-12",
  "Electric Utilities",
  "Electric Power Generation",
  "Fossil Fuel Power Generation",
  "Nuclear Power Generation",
  "Solar Power Generation",
  "Wind Power Generation",
  "Electric Power Transmission, Distribution & Marketing",
  "Finance & Insurance Sector",
  "Asset Management",
  "Custodial & Trust",
  "Mutual Fund Management",
  "Retirement & Pension Management",
  "Banks & Credit Unions",
  "Financial Planners & Investment Advisers",
  "Financial Transaction Processing",
  "Hedge Fund Management",
  "Insurance Agencies & Brokerages",
  "Insurance Carriers",
  "Health Insurance Carriers",
  "Life Insurance Carriers",
  "Property/Casualty Insurance Carriers",
  "Reinsurance Carriers",
  "Title Insurance Carriers",
  "Investment Banking",
  "Lending",
  "Auto Lending",
  "Consumer Lending",
  "Credit Cards",
  "Mortgage Banking",
  "Securities Brokerages",
  "Stock Exchanges",
  "Venture Capital",
  "Government",
  "US Municipal Governments",
  "Health Care Sector",
  "Ambulatory Health Care",
  "Ambulance",
  "Anesthesiologists",
  "Cardiologists",
  "Chiropractors",
  "Dentists",
  "Dermatologists",
  "General Surgeons",
  "life Health Care",
  "Kidney Dialysis Centers",
  "Medical & Diagnostic Laboratories",
  "Mental Health & Substance Abuse",
  "Mental Health Professionals",
  "OBGYNs",
  "Oncologists",
  "Optometrists",
  "Outpatient Surgical Centers",
  "Pediatricians",
  "Physicians",
  "Podiatrists",
  "Rehabilitation Therapy",
  "Hospitals",
  "Nursing lifes & Long-Term Care Facilities",
  "Social Assistance",
  "Child Care",
  "Lodging",
  "Bed & Breakfast Inns",
  "Hotels, Motels & Resorts",
  "Recreational Vehicle Parks",
  "Management of Companies & Enterprises",
  "Investment Firms",
  "Manufacturing Sector",
  "Apparel Manufacturing",
  "Apparel Accessories Manufacturing",
  "Footwear Manufacturing",
  "Men's Clothing Manufacturing",
  "Women's Clothing Manufacturing",
  "Audio & Video Equipment Manufacturing",
  "Breweries",
  "Chemical Manufacturing",
  "Agricultural Chemical Manufacturing",
  "Biofuel Manufacturing",
  "Industrial Chemical Manufacturing",
  "Paint & Coating Manufacturing",
  "Plastic Resin & Synthetic Fiber Manufacturing",
  "Commercial Printing",
  "Computer Manufacturing",
  "Personal Computer Manufacturing",
  "Computer Networking Equipment Manufacturing",
  "Wireless Networking Equipment Manufacturing",
  "Computer Peripheral Equipment Manufacturing",
  "Navigational Instruments Manufacturing",
  "Monitoring Instruments Manufacturing",
  "Measurement Instruments Manufacturing",
  "Technical Instruments Manufacturing",
  "Guidance System Manufacturing",
  "Data Storage Systems Manufacturing",
  "Distilleries",
  "Electrical Products Manufacturing",
  "Battery Manufacturing",
  "Household Appliance Manufacturing",
  "Industrial Control Products Manufacturing",
  "Lighting Equipment Manufacturing",
  "Motor & Generator Manufacturing",
  "SWiring Device Manufacturing",
  "Transformer Manufacturing",
  "X-Ray Apparatus Manufacturing",
  "Eyewear Manufacturing",
  "Fabricated Metal Product Manufacturing",
  "Architectural & Structural Metals Manufacturing",
  "Gun & Ammunition Manufacturing",
  "Handtool, Cutlery, & Flatware Manufacturing",
  "Hardware & Fastener Manufacturing",
  "Machine Shops",
  "Metal Coating, Engraving & Heat Treating",
  "Metal Valve & Pipe Fitting Manufacturing",
  "Food Manufacturing",
  "Bakery Product Manufacturing",
  "Breakfast Cereal Manufacturing ",
  "Candy Manufacturing",
  "Coffee & Tea Manufacturing",
  "Cookie & Cracker Manufacturing",
  "Dairy Products Manufacturing",
  "Edible Oils Manufacturing",
  "Fresh Prepared Foods",
  "Fruit & Vegetable Processing",
  "Grain Milling",
  "Livestock & Other Animal Food Manufacturing",
  "Meat Product Manufacturing",
  "Pet Food Manufacturing",
  "Poultry Product Manufacturing",
  "Seafood Processing",
  "Seasoning & Dressing Manufacturing",
  "Snack Foods Manufacturing",
  "Sugar Manufacturing",
  "Furniture Manufacturing",
  "Office Furniture, Fixtures & Equipment Manufacturing",
  "HVAC Equipment Manufacturing",
  "Jewelry Manufacturing",
  "Machinery Manufacturing",
  "Agricultural Machinery Manufacturing ",
  "Construction Machinery Manufacturing",
  "Food Product Machinery Manufacturing",
  "Material Handling Equipment Manufacturing",
  "Metalworking Machinery Manufacturing",
  "Oil & Gas Field Equipment Manufacturing",
  "Photographic & Optical Equipment/Supplies Manufacturing",
  "Power Tool & Lawn/Garden Equipment Manufacturing",
  "Printing Machinery & Equipment Manufacturing ",
  "Semiconductor Equipment Manufacturing",
  "Turbine Manufacturing",
  "Magnetic & Optical Media Manufacturing & Reproduction",
  "Magnetic & Optical Media Manufacturing",
  "Mattress Manufacturing",
  "Medical Equipment & Supplies Manufacturing",
  "Musical Instrument Manufacturing",
  "Nonalcoholic Beverage Manufacturing ",
  "Soft Drink Manufacturing",
  "Water & Ice Manufacturing",
  "Nonmetallic Mineral Product Manufacturing",
  "Abrasives Manufacturing",
  "Cement & Concrete Product Manufacturing",
  "China & Earthenware Plumbing Fixture Manufacturing",
  "Clay Product & Refractory Manufacturing",
  "Glass & Glass Product Manufacturing",
  "Office, School & Art Supplies Manufacturing",
  "Paper & Paper Products Manufacturing",
  "Converted Paper Products Manufacturing",
  "Pulp & Paper Mills",
  "Personal Care Products Manufacturing",
  "Petroleum & Coal Products Manufacturing",
  "Asphalt Products Manufacturing",
  "Petroleum Refining",
  "Pharmaceutical Manufacturing",
  "Biotechnology Product Manufacturing",
  "Diagnostic Substance Manufacturing",
  "Nutritional Supplement Product Manufacturing",
  "Plastic & Rubber Product Manufacturing",
  "Tire Manufacturing",
  "Primary Metals Manufacturing",
  "Aluminum Production",
  "Steel Production",
  "Security Products Manufacturing",
  "Semiconductor Manufacturing",
  "Sign Manufacturing",
  "Soap & Other Detergent Manufacturing",
  "Sporting Goods Manufacturing",
  "Fitness Equipment Manufacturing",
  "Telecommunications Equipment Manufacturing",
  "Wireless Telecommunications Equipment Manufacturing",
  "Textile Manufacturing",
  "Carpet & Rug Manufacturing",
  "Linens Manufacturing",
  "Tobacco Product Manufacturing",
  "Toy & Game Manufacturing",
  "Electronic Toys & Games Manufacturing",
  "Transportation Equipment Manufacturing",
  "Aerospace Products & Parts Manufacturing",
  "Aircraft Engine & Parts Manufacturing",
  "Armored Military Vehicle Manufacturing ",
  "Automobile Manufacturing",
  "Automobile Parts Manufacturing",
  "Boat Building",
  "Guided Missile & Space Vehicle Manufacturing",
  "Motorcycle Manufacturing ",
  "Railroad Equipment Manufacturing",
  "Recreational Vehicle Manufacturing",
  "Shipbuilding & Repairing",
  "Truck & Bus Manufacturing",
  "Truck Trailer Manufacturing",
  "Wineries",
  "Wood Product Manufacturing",
  "Lumber & Plywood Product Manufacturing",
  "Manufactured life Manufacturing",
  "Prefabricated Wood Building Manufacturing",
  "Wood Flooring Manufacturing",
  "Wood Window & Door Manufacturing",
  "Media",
  "Computer Software",
  "Accounting & Finance Software",
  "Business Intelligence Software",
  "Content & Document Management Software",
  "Customer Relationship Management, Marketing & Sales Software",
  "Database & File Management Software",
  "Development Tools, Operating Systems & Utilities Software",
  "E-commerce Software",
  "Education & Training Software",
  "Engineering, Scientific & CAD/CAM Software",
  "Enterprise Resource Planning Software",
  "Entertainment & Games Software",
  "Health Care Management Software",
  "Human Resources & Workforce Management Software",
  "Messaging, Conferencing & Communications Software",
  "Multimedia, Graphics & Publishing Software",
  "Security Software",
  "Supply Chain Management & Logistics Software",
  "Film & Video",
  "Motion Picture Production & Distribution",
  "Movie Theaters",
  "Special Effects & Other Video Post-Production",
  "TV Program Production & Distribution",
  "Internet Publishing, Broadcasting & Search Portals",
  "Managed Application & Network",
  "Music Production & Distribution",
  "Publishing",
  "Book Publishers",
  "Directory & Mailing List Publishers",
  "Greeting Card Publishers",
  "Magazine Publishers",
  "Newspaper Publishers",
  "Radio Broadcasting & Programming",
  "Telecommunications",
  "Telecommunications Resellers",
  "Wired Telecommunications",
  "Wireless Telecommunications",
  "Television Broadcasting",
  "TV Broadcast & Cable Networks",
  "Membership Organizations",
  "Business & Professional Associations",
  "lifeowner Associations",
  "Labor Unions",
  "Mining",
  "Coal Mining",
  "Metal Ore Mining",
  "Copper & Nickel Mining",
  "Gold & Silver Mining",
  "Nonmetallic Mineral Mining & Quarrying",
  "Natural Gas Distribution & Marketing",
  "Nonclassifiable establishments",
  "Nonprofit Institutions",
  "Grantmaking Foundations",
  "Health Fund-raising Organizations",
  "Oil & Gas Exploration & Production",
  "Oil & Gas Field",
  "Oil & Gas Well Drilling",
  "Private Households",
  "Professional Services Sector",
  "Accounting",
  "Payroll",
  "Advertising & Marketing",
  "Advertising Agencies",
  "Digital Advertising",
  "Direct Marketing",
  "Public Relations",
  "Sales Promotion",
  "Architectural & Engineering",
  "Architectural",
  "Engineering",
  "Erosion Control",
  "Consulting",
  "Environmental Consulting",
  "Human Resources Consulting",
  "Geophysical Surveying & Mapping",
  "Graphic Design",
  "Information Technology",
  "Interior Design",
  "Legal",
  "Market Research & Polling",
  "Photographic",
  "Scientific Research & Development",
  "Biotechnology Research",
  "Testing Laboratories",
  "Veterinary",
  "Real Estate",
  "Commercial Real Estate Brokerage",
  "Commercial Real Estate Management",
  "Real Estate Investment Trusts (REITs)",
  "Residential Property Investment",
  "Residential Real Estate Brokerage & Management",
  "Self-Storage Services ",
  "Religious Organizations",
  "Rental & Leasing",
  "Aircraft Leasing",
  "Automobile Rental & Leasing",
  "Truck Rental & Leasing",
  "Commercial & Industrial Equipment Rental & Leasing",
  "Consumer Product Rental",
  "Technology & Office Equipment Leasing",
  "Restaurants, Bars & Food",
  "Bars & Nightclubs",
  "Catering Services ",
  "Food Service",
  "Restaurants",
  "Casual Restaurants",
  "Coffee Shops",
  "Fast-Food & Quick-Service Restaurants",
  "Specialty Eateries",
  "Retail Sector",
  "Art Dealers & Galleries ",
  "Automobile Dealers",
  "Luxury Automobile Dealers",
  "Automotive Parts & Accessories Stores",
  "Tire Dealers",
  "Beer, Wine & Liquor Stores",
  "Boat Dealers",
  "Bookstores",
  "Building Material Dealers",
  "life Centers & Hardware Stores",
  "Paint & Wallpaper Stores",
  "Clothing Stores",
  "Shoe Stores",
  "Consumer Electronics & Appliances Stores",
  "Household Appliance Stores",
  "Convenience Stores & Truck Stops",
  "Gas Stations",
  "Cosmetics, Beauty Supply & Perfume Stores",
  "Department Stores",
  "Discount Department Stores ",
  "Dollar & Other General Merchandise Stores",
  "Drug Stores",
  "Health Supplement Stores",
  "Florists",
  "Fuel Oil & LP Gas Dealers",
  "Garden Centers & Farm Supply Stores",
  "Gift, Novelty & Souvenir Stores",
  "Grocery Stores & Supermarkets",
  "Specialty Food Stores",
  "life Furniture & Housewares Stores",
  "Furniture Stores",
  "life Furnishings Stores",
  "Jewelry Stores",
  "Motorcycle Dealers",
  "Musical Instrument Stores",
  "Nonstore Retail",
  "Direct Selling",
  "Internet & Mail-Order Retail",
  "Internet Auctions",
  "Office Supply Stores",
  "Opticians",
  "Pet & Pet Supplies Stores",
  "Recreational Vehicle Dealers",
  "Sporting Goods Stores",
  "Toy & Hobby Stores",
  "Used Merchandise Stores",
  "Vending Machine Operators",
  "Warehouse Clubs & Superstores",
  "Transportation Services Sector",
  "Airlines",
  "Airport Operations",
  "Aircraft Maintenance & Repair",
  "Bus Transportation",
  "Charter & Other Nonscheduled Air Transportation",
  "Commuter Rail Systems",
  "Express Delivery",
  "Freight Forwarding",
  "Motor Vehicle Towing",
  "Moving",
  "Oil & Gas Transportation & Storage",
  "Crude Petroleum Pipelines",
  "Natural Gas Pipelines",
  "Refined Petroleum Pipelines",
  "Port, Harbor & Marine Terminal Management",
  "Postal",
  "Railroads",
  "Specialty Trucking",
  "Taxi & Limousine",
  "Trucking",
  "Less-Than-Truckload Carriers",
  "Truckload Carriers",
  "Warehousing & Storage",
  "Information & Records Management",
  "Water Transportation",
  "Coastal & Great Lakes Freight Transportation",
  "Cruise Ships ",
  "Deep Sea Freight Transportation",
  "Inland Water Freight Transportation",
  "Water & Sewer Utilities",
  "Wholesale Sector",
  "Beer, Wine & Distilled Spirits Wholesalers",
  "Chemical Wholesalers",
  "Computer & Office Equipment Wholesalers ",
  "Drug Wholesalers ",
  "Prescription Benefits Management",
  "Electrical, Plumbing & Hardware Wholesalers",
  "Electrical Products Wholesalers",
  "Electronic Component Wholesalers",
  "Farm & Garden Equipment Wholesalers",
  "Food Wholesalers",
  "Fresh Produce Wholesalers",
  "Industrial Equipment Wholesalers",
  "Industrial Supply Wholesalers",
  "Lumber Wholesalers",
  "Medical Equipment & Supply Wholesalers",
  "Office Supply Wholesalers",
  "Petroleum wholesaler",
  "Recyclable Material Wholesaler",
  "Steelworker",
  "Tire Wholesaler"
];
var relationquals = [
  "abusive",
  "affectionate",
  "argumentative",
  "co-dependent",
  "communicative",
  "unremarkable",
  "controlling",
  "casual",
  "distant",
  "harmonious",
  "hateful",
  "lively",
  "loving",
  "manipulative",
  "meaningful",
  "melodramatic",
  "playful",
  "difficult",
  "resentful",
  "reserved",
  "shaky",
  "simpatico",
  "solid",
  "superficial",
  "supportive",
  "turbulent",
  "unequal",
  "violent",
  "argumentative"
];
var intros = [
  "through family",
  "as classmates",
  "as coworkers",
  "through a mutual friend",
  "through a newspaper ad",
  "through an online ad",
  "through a social group",
  "through a shared fandom",
  "through a shared hobby",
  "as neighbors"
];
var attachments = [
  "casual",
  "intimate",
  "neutral",
  "onesided",
  "strong",
  "tolerable",
  "uneasy"
];
var relationships = [
  "celibate",
  "monogamous",
  "polyamorous",
  "promiscuous",
  "unfaithful"
];
var statusrels = [
  "engaged to",
  "married to",
  "divorced from",
  "separated from",
  "cohabitating with",
  "in a long-distance affair with",
  "casually dating",
  "widowed, and late parter was"
];
var ratequalitys = [
  "poorly",
  "adequately",
  "well",
  "very well",
  "exceptionally"
];
</script>
