<template >
  <div id="character" class="page-body">
    <div class="container">
      <p class="aftertitle">All values are selected at random and independent of other selections in the output. This may result in some unusual combinations.</p>

      <div class="row extra-after">
        <div class="three columns bordertop-th"><button class="button" v-on:click="rollDice('one')">generate</button></div>
        <div class="three columns bordertop-th"><button class="button" v-on:click="rollDice('two')">generate</button></div>
        <div class="three columns bordertop-th"><button class="button" v-on:click="rollDice('three')">generate</button></div>
        <div class="three columns bordertop-th"><button class="button" v-on:click="rollDice('four')">generate</button></div>
      </div>
      <div class="row bordertop">
        <div class="three columns"><h5>general</h5><p v-bind:key="d" v-for="d in character.one.base">{{d}}</p></div>
        <div class="three columns"><h5>general</h5><p v-bind:key="d" v-for="d in character.two.base">{{d}}</p></div>
        <div class="three columns"><h5>general</h5><p v-bind:key="d" v-for="d in character.three.base">{{d}}</p></div>
        <div class="three columns"><h5>general</h5><p v-bind:key="d" v-for="d in character.four.base">{{d}}</p></div>
      </div>
      <div class="row bordertop">
        <div class="three columns"><h5>Face</h5><p v-bind:key="d" v-for="d in character.one.face">{{d}}</p></div>
        <div class="three columns"><h5>Face</h5><p v-bind:key="d" v-for="d in character.two.face">{{d}}</p></div>
        <div class="three columns"><h5>Face</h5><p v-bind:key="d" v-for="d in character.three.face">{{d}}</p></div>
        <div class="three columns"><h5>Face</h5><p v-bind:key="d" v-for="d in character.four.face">{{d}}</p></div>
      </div>
      <div class="row bordertop">
        <div class="three columns"><h5>Emotional traits</h5><p v-bind:key="d" v-for="d in character.one.emotion">{{d}}</p></div>
        <div class="three columns"><h5>Emotional traits</h5><p v-bind:key="d" v-for="d in character.two.emotion">{{d}}</p></div>
        <div class="three columns"><h5>Emotional traits</h5><p v-bind:key="d" v-for="d in character.three.emotion">{{d}}</p></div>
        <div class="three columns"><h5>Emotional traits</h5><p v-bind:key="d" v-for="d in character.four.emotion">{{d}}</p></div>
      </div>
      <div class="row bordertop">
        <div class="three columns"><h5>mental traits</h5><p>{{character.one.mental}}</p></div>
        <div class="three columns"><h5>mental traits</h5><p>{{character.two.mental}}</p></div>
        <div class="three columns"><h5>mental traits</h5><p>{{character.three.mental}}</p></div>
        <div class="three columns"><h5>mental traits</h5><p>{{character.four.mental}}</p></div>
      </div>
      <div class="row bordertop">
        <div class="three columns"><h5>physical traits</h5><p v-bind:key="d" v-for="d in character.one.physkill">{{d}}</p></div>
        <div class="three columns"><h5>physical traits</h5><p v-bind:key="d" v-for="d in character.two.physkill">{{d}}</p></div>
        <div class="three columns"><h5>physical traits</h5><p v-bind:key="d" v-for="d in character.three.physkill">{{d}}</p></div>
        <div class="three columns"><h5>physical traits</h5><p v-bind:key="d" v-for="d in character.four.physkill">{{d}}</p></div>
      </div>
      <div class="row bordertop">
        <div class="three columns"><h5>favorite things</h5><ul><li v-bind:key="d" v-for="d in character.one.faves">{{d}}</li></ul></div>
        <div class="three columns"><h5>favorite things</h5><ul><li v-bind:key="d" v-for="d in character.two.faves">{{d}}</li></ul></div>
        <div class="three columns"><h5>favorite things</h5><ul><li v-bind:key="d" v-for="d in character.three.faves">{{d}}</li></ul></div>
        <div class="three columns"><h5>favorite things</h5><ul><li v-bind:key="d" v-for="d in character.four.faves">{{d}}</li></ul></div>
      </div>
      <div class="row bordertop">
        <div class="three columns"><h5>Personality Quirks</h5><ul><li v-bind:key="d" v-for="d in character.one.quirk">{{d}}</li></ul></div>
        <div class="three columns"><h5>Personality Quirks</h5><ul><li v-bind:key="d" v-for="d in character.two.quirk">{{d}}</li></ul></div>
        <div class="three columns"><h5>Personality Quirks</h5><ul><li v-bind:key="d" v-for="d in character.three.quirk">{{d}}</li></ul></div>
        <div class="three columns"><h5>Personality Quirks</h5><ul><li v-bind:key="d" v-for="d in character.four.quirk">{{d}}</li></ul></div>
      </div>
      <div class="row bordertop">
        <div class="three columns"><h5>Magical Quirks</h5><ul><li v-bind:key="d" v-for="d in character.one.magic">{{d}}</li></ul></div>
        <div class="three columns"><h5>Magical Quirks</h5><ul><li v-bind:key="d" v-for="d in character.two.magic">{{d}}</li></ul></div>
        <div class="three columns"><h5>Magical Quirks</h5><ul><li v-bind:key="d" v-for="d in character.three.magic">{{d}}</li></ul></div>
        <div class="three columns"><h5>Magical Quirks</h5><ul><li v-bind:key="d" v-for="d in character.four.magic">{{d}}</li></ul></div>
      </div>
    </div>
  </div>
</template>

<script>
/*  eslint-disable quotes  */

export default {
  name: 'character',
  data () {
    return {
      isActive: true,
      character: {
        one: {},
        two: {},
        three: {},
        four: {}
      }
    }
  },
  methods: {
    rollDice: function(val) {
      this.type = this.typeFactory();
      var dice = {
        val: val,
        base: this.baseFactory(val),
        face: this.faceFactory(val),
        physkill: this.physicalFactory(val),
        emotion: this.emotionsFactory(val),
        quirk: this.quirksFactory(),
        magic: this.magicsFactory(),
        mental: this.mindsFactory(val),
        faves: this.favesFactory()
      }
      this.character[val] = dice;
    },
    shuffle: function(o) {
      for (var j, x, i = o.length; i; j = Math.floor(Math.random() * i), x = o[--i], o[i] = o[j], o[j] = x);
      return o;
    },
    typeFactory: function() {
      var typeval = Math.floor(Math.random() * 100);
      this.type = {};
      if (typeval < 50) {
        if (typeval < 2) {
          this.type = types[4];
        } else if (typeval < 4) {
          this.type = types[5];
        } else if (typeval < 6) {
          this.type = types[1];
        } else {
          this.type = types[0];
        }
      } else {
        if (typeval > 98) {
          this.type = types[4];
        } else if (typeval > 96) {
          this.type = types[5];
        } else if (typeval > 94) {
          this.type = types[3];
        } else {
          this.type = types[2];
        }
      }
      return this.type;
    },
    baseFactory: function(val) {
      var arr = [];
      this.character[val].name = this.shuffle(names[val])[0];
      var age = Math.floor(Math.random() * (81)) + 10;
      var baseSet1 = this.character[val].name + ' is a ' + this.shuffle(mind.attitudes)[0] + ' ' + age + '-year-old ' + this.type.name + ' with ' + this.shuffle(body.tones)[0] + ' skin, ' +
         ' and a ' + this.shuffle(mind.outlooks)[0] + ' outlook on life.';
      var baseSet2 = this.shuffle(body.heights)[0] + ' and ' + this.shuffle(body.weights)[0] + ', ' + this.character[val].name + ' has a ' +
        this.shuffle(body.shapes)[0] + ' build, and ' + this.shuffle(freqs)[0] + ' dresses in a ' + this.shuffle(body.clothings)[0] + ' style. ';
      arr.push(baseSet1, baseSet2);
      return arr;
    },
    mindsFactory: function(val) {
      var mindSet = this.character[val].name + ' has ';
      var num = Math.floor(Math.random() * (10) + 1);
      if (num > 5) {
        mindSet += 'average';
      } else {
        mindSet += this.shuffle(intelligences)[0];
      }
      mindSet += ' intelligence. ' + this.character[val].name + ' has ' + this.shuffle(schoolings)[0] + ' education and ' + this.shuffle(educations)[0] + '. ' +
        this.character[val].name + ' ' + this.shuffle(knowledges)[0] + '.';
      return mindSet;
    },
    favesFactory: function() {
      var faveSet = [];
      faveSet.push('color: ' + this.shuffle(faves.colors)[0]);
      faveSet.push('time of day: ' + this.shuffle(faves.days)[0]);
      faveSet.push('environment: ' + this.shuffle(faves.environments)[0]);
      faveSet.push('day-off activity: ' + this.shuffle(faves.holidays)[0]);
      faveSet.push('room in house: ' + this.shuffle(faves.rooms)[0]);
      faveSet.push('season: ' + this.shuffle(faves.seasons)[0]);
      faveSet.push('weather: ' + this.shuffle(faves.weathers)[0]);
      return faveSet;
    },
    faceFactory: function(val) {
      var arr = [];
      var faceSet1 = '';
      var faceSet3 = '';
      faceSet1 = this.character[val].name + ' has ' + this.shuffle(body.faceshapes)[0];
      num = Math.floor(Math.random() * 10);
      if (num < 6) {
        faceSet1 += ', ' + this.shuffle(body.facemores)[0];
      }
      num = Math.floor(Math.random() * 10);
      if (num < 5) {
        faceSet1 += ', ' + this.shuffle(body.teeths)[0];
      }
      faceSet1 += ', ' + this.shuffle(body.eyedetails1)[0] + ' ' + this.shuffle(body.eyecolors)[0] + ' eyes, and a ' + this.shuffle(body.foreheads)[0] + '. ' +
        this.character[val].name + '’s hair is ' + this.shuffle(body.hairlengths)[0] + ', ' + this.shuffle(body.hairtypes)[0] + ', and ' + this.shuffle(body.haircolors)[0];
      num = Math.floor(Math.random() * 10);
      if (num < 4) {
        faceSet1 += ', with ' + this.shuffle(body.hairdyes)[0];
      }
      num = Math.floor(Math.random() * 10);
      if (num < 6) {
        faceSet1 += ', ' + this.shuffle(freqs)[0] + ' ' + this.shuffle(body.hairstyles)[0];
      }
      faceSet1 += '. ';
      num = Math.floor(Math.random() * 30);
      if (num < 5) {
        faceSet1 += this.character[val].name + ' ' + this.shuffle(freqs)[0] + ' wears ' + this.shuffle(body.eyedetails2)[0] + '. ';
      }
      faceSet3 = 'Other notable features include ' + this.shuffle(body.lips)[0];
      num = Math.floor(Math.random() * 10);
      if (num < 3) {
        faceSet3 += ', a habit of wearing ' + this.shuffle(body.lipsticks)[0];
      }
      num = Math.floor(Math.random() * 10);
      if (num < 4) {
        faceSet3 += ', ' + this.shuffle(body.chins)[0];
      }
      if (num < 3) {
        num = Math.floor(Math.random() * 10);
        if (num < 4) {
          faceSet3 += ', ' + this.shuffle(body.facehairs)[0];
        }
      } else {
        num = Math.floor(Math.random() * 60);
        if (num < 4) {
          faceSet3 += ', ' + this.shuffle(body.facehairs)[0];
        }
      }
      faceSet3 += ', ' + this.shuffle(body.skindetails1)[0] + ' skin, a ' + this.shuffle(body.noses)[0] + ', and ' + this.shuffle(body.eyebrows)[0] + ' brows.';
      arr.push(faceSet1, faceSet3);
      return arr;
    },
    emotionsFactory: function(val) {
      var arr = [];
      var emoSet1 = '';
      var emoSet2 = '';
      var emoSet3 = '';
      var expression = this.shuffle(mind.expressions);
      var emotion = this.shuffle(mind.emotions);
      emoSet1 = 'When dealing with interpersonal conflict, ' + this.character[val].name + ' prefers to ' + this.shuffle(mind.conflictverbals)[0] + '. In physical confrontations, ' + this.character[val].name + ' ' + this.shuffle(mind.conflicts)[0] + '.';
      emoSet2 = 'Given a choice, ' + this.character[val].name + ' will ' + this.shuffle(mind.reactions)[0] + '.';
      emoSet3 = this.character[val].name + '’s most common emotional states are ' + emotion[0] + ', which ' + expression[0] + '; ' + emotion[1] + ', which ' + expression[1] + '; and ' + emotion[2] + ', which ' + expression[2] + '.';
      arr.push(emoSet1, emoSet2, emoSet3);
      return arr;
    },
    physicalFactory: function(val) {
      var arr = [];
      var phySet1 = '';
      var phySet2 = '';
      var phySet3 = '';
      phySet1 = this.character[val].name + ' is ';
      num = Math.floor(Math.random() * 100);
      if (num < 3) {
        phySet1 += 'ambidextrous';
      } else if (num < 10) {
        phySet1 += 'left-handed';
      } else {
        phySet1 += 'right-handed';
      }
      phySet1 += ' and ' + this.shuffle(freqs)[0] + ' ' + this.shuffle(body.gestures)[0] + '. When moving, ' + this.character[val].name + ' ' +
        this.shuffle(body.movements)[0] + ', when still, ' + this.character[val].name + ' ' + this.shuffle(body.stances)[0] + '.';
      var ratequality = this.shuffle(ratequalitys);
      var physkill = this.shuffle(body.physkills);
      phySet2 = 'Generally, ' + this.character[val].name + ' has ' + ratequality[0] + ' ' + physkill[0] + ', ' + ratequality[1] + ' ' +
        physkill[1] + ', and ' + ratequality[2] + ' ' + physkill[2] + '. ';
      num = Math.floor(Math.random() * (10) + 1);
      if (num > 6) {
        phySet3 += this.character[val].name + ' also has ' + this.shuffle(body.disabilityphys)[0] + '. ';
      }
      arr.push(phySet1, phySet2);
      var optmark = [];
      var optmark2 = [];
      var markSet = '';
      var skindetail2 = this.shuffle(body.skindetails2);
      markSet = this.character[val].name + ' has ';
      num = Math.floor(Math.random() * 20);
      if (num > 17) {
        optmark.push(skindetail2[0] + ' on the ' + this.shuffle(body.leftrights)[0] + ' ' + this.shuffle(body.bodyparts2)[0]);
      }
      num = Math.floor(Math.random() * 20);
      if (num > 17) {
        optmark.push(skindetail2[1] + ' on the ' + this.shuffle(body.bodyparts1)[0]);
      }
      num = Math.floor(Math.random() * 10);
      if (num < 3) {
        num = Math.floor(Math.random() * 5);
        var piercing = this.shuffle(body.piercings);
        for (var g = 0; g < num; g++) {
          optmark.push(piercing[g]);
        };
      }
      if (optmark.length > 1) {
        for (i = 0; i < optmark.length; i++) {
          i < (optmark.length - 1) ? markSet += optmark[i] + ', ' : markSet += ' and ' + optmark[i];
        }
      }
      if (optmark.length === 1) {
        markSet += optmark[0];
      } else {
        markSet += 'no distinguishing scars or birthmarks, and no piercings';
      }
      num = Math.floor(Math.random() * 10);
      if (num < 3) {
        var bodypart2 = this.shuffle(body.bodyparts2);
        num = Math.floor(Math.random() * 5);
        for (var j = 0; j < num; j++) {
          optmark2.push(this.shuffle(body.leftrights)[0] + ' ' + bodypart2[j]);
        }
      }
      num = Math.floor(Math.random() * 10);
      if (num < 3) {
        var bodypart1 = this.shuffle(body.bodyparts1);
        num = Math.floor(Math.random() * 5);
        for (var k = 0; k < num; k++) {
          optmark2.push(bodypart1[k]);
        }
      }
      markSet += '. ' + this.character[val].name + ' has ';
      if (optmark2.length > 1) {
        markSet += 'tattoos on the ';
        for (i = 0; i < optmark2.length; i++) {
          i < (optmark2.length - 1) ? markSet += optmark2[i] + ', ' : markSet += ' and ' + optmark2[i];
        }
      } else if (optmark2.length === 1) {
        markSet += 'a tattoo on the ' + optmark2[0];
      } else {
        markSet += 'no tattoos';
      }
      markSet += '.';
      arr.push(markSet, phySet3);
      return arr;
    },
    quirksFactory: function(val) {
      var arr = [];
      var quirk = this.shuffle(quirks);
      for (var a = 0; a < 3; a++) {
        arr.push(quirk[a]);
      }
      var quirkarray = ['attires', 'beliefs', 'collections', 'disdains', 'drinks', 'eats', 'fidgets', 'finances', 'greets', 'hands', 'hates', 'humors', 'intuitions', 'laws', 'lies', 'literacys', 'refuses', 'relates', 'relaxings', 'sleeps', 'speechs', 'storys', 'times'];
      var allquirks = this.shuffle(quirkarray);
      var mix0 = allquirks[0];
      arr.push(this.shuffle(otherquirks[mix0])[0]);
      var mix1 = allquirks[1];
      arr.push(this.shuffle(otherquirks[mix1])[0]);
      var mix2 = allquirks[2];
      arr.push(this.shuffle(otherquirks[mix2])[0]);
      return arr;
    },
    magicsFactory: function(val) {
      var arr = [];
      var magic = this.shuffle(quirkmagis);
      for (var a = 0; a < 3; a++) {
        arr.push(magic[a]);
      }
      return arr;
    }
  }
};
var i = 0;
var num = 0;
var types = [
  {value: 0, name: "woman", tval: 1},
  {value: 1, name: "trans woman", tval: 1},
  {value: 2, name: "man", tval: 0},
  {value: 3, name: "trans man", tval: 0},
  {value: 4, name: "agender person", tval: 2},
  {value: 5, name: "androgynous person", tval: 2}
];
var freqs = [
  "usually",
  "sometimes",
  "often",
  "occasionally"
];
var ratequalitys = [
  "poor",
  "adequate",
  "average",
  "very good",
  "exceptional"
];
var body = {
  'shapes': [
    'small-boned',
    'solid',
    'medium',
    'rounded',
    'soft',
    'angular'
  ],
  'heights': [
    'Very tall',
    'Slighty taller than average',
    'Of average height',
    'Slightly shorter than average',
    'Very short'
  ],
  'weights': [
    'emaciated',
    'underweight',
    'slightly underweight',
    'average weight',
    'slightly overweight',
    'overweight',
    'obese'
  ],
  'skindetails1': [
    'burned',
    'flushed',
    'freckled',
    'pocked',
    'reddened',
    'rough',
    'sallow',
    'sickly',
    'smooth',
    'tanned',
    'wrinkled'
  ],
  'skindetails2': [
    'acne scars',
    'a birthmark',
    'a scar',
    'a mole',
  ],
  'tones': [
    'light-pale',
    'light-olive',
    'light-ruddy',
    'medium-brown',
    'medium-olive',
    'medium-ruddy',
    'dark-brown',
    'dark-olive',
    'dark-ruddy',
    'dark-black'
  ],
  'facemores': [
    'smile lines',
    'high cheekbones',
    'dimple',
    'frown lines',
    'prominent adam’s apple',
    'sunken cheeks',
    'thick neck',
    'round cheeks',
  ],
  'foreheads': [
    'broad forehead',
    'creased brow',
    'high forehead',
    'receding hairline',
    'widow’s peak',
    'lined forehead',
    'smooth forehead'
  ],
  'faceshapes': [
    'a diamond-shaped face',
    'a heart-shaped face',
    'a long face',
    'an oval face',
    'a round face',
    'a square face',
  ],
  'eyecolors': [
    'amber',
    'dark brown',
    'light brown',
    'green',
    'light blue',
    'dark blue',
    'blue-green',
    'gray',
    'hazel-green',
    'hazel-brown',
    'hazel-blue',
    'heterochromatic',
    'milky'
  ],
  'eyedetails1': [
    'angled',
    'bulging',
    'close-set',
    'deep-set',
    'single-lidded',
    'large',
    'shadowed',
    'reddened',
    'round',
    'small',
    'pinched',
    'squinched',
    'sunken',
    'watery',
    'narrow',
    'wide-set',
    'wrinkled',
    'bagged',
  ],
  'eyedetails2': [
    'contact lenses',
    'colored contacts',
    'fashion contacts',
    'fashion glasses',
    'reading glasses',
    'thick glasses',
    'sunglasses',
    'an eyepatch'
  ],
  'eyebrows': [
    'arched',
    'bushy',
    'dark',
    'fair',
    'shaved',
    'thin',
    'unibrow'
  ],
  'noses': [
    'broken nose',
    'bulbous nose',
    'crooked nose',
    'flat nose',
    'hawk nose',
    'hooked nose',
    'large nose',
    'wide nose',
    'narrow nose',
    'bent nose',
    'short nose',
    'small nose',
    'snub nose',
    'turned-up nose'
  ],
  'lips': [
    'chapped lips',
    'cleft palate',
    'a hairlip',
    'bitten lips',
    'curled-down lips',
    'curled-up lips',
    'full lips',
    'large lips',
    'puffy lips',
    'a rosebud mouth',
    'stained lips',
    'thin lips',
    'firm lips',
    'a crooked smile'
  ],
  'lipsticks': [
    'dark lipstick',
    'glossy lipstick',
    'smeared lipstick',
    'chapstick',
    'lip balm'
  ],
  'teeths': [
    'an overbite',
    'broken teeth',
    'crooked teeth',
    'stained teeth',
    'straight teeth',
    'yellow teeth',
    'an underbite',
    'braces',
    'gold-capped teeth',
    'white teeth',
    'false teeth',
    'missing teeth'
  ],
  'chins': [
    'a recessed chin',
    'a strong jaw',
    'jowls',
    'a jutting chin',
    'a double chin',
    'a chin cleft'
  ],
  'hairlengths': [
    'buzzcut',
    'cropped',
    'short',
    'chin-length',
    'shoulder-length',
    'elbow-length',
    'waist-length'
  ],
  'haircolors': [
    'light blond',
    'dark blond',
    'strawberry blond',
    'medium red',
    'auburn',
    'light brown',
    'medium brown',
    'dark brown',
    'black-brown',
    'black-blue',
    'silver',
    'gray',
    'salt-and-pepper',
    'bright red',
    'bleached blond',
  ],
  'hairdyes': [
    'colorful streaks',
    'a single streak',
    'lowlights',
    'highlights',
    'visible roots',
    'a visible dye-line'
  ],
  'hairtypes': [
    'coarse',
    'naturally curly',
    'permed',
    'fine',
    'frizzy',
    'chemically straightened',
    'straight',
    'thick',
    'thin',
    'wavy',
    'wiry'
  ],
  'hairstyles': [
    'cornrowed',
    'braided',
    'feathered',
    'pigtailed',
    'ponytailed',
    'slicked',
    'neat',
    'tangled',
    'gelled',
    'greasy',
    'hairsprayed',
    'matted',
    'messy',
  ],
  'facehairs': [
    'beard',
    'goatee',
    'mustache',
    'mustache, pencil',
    'mustache, walrus',
    'mutton-chops',
    'sideburns',
    'soul patch',
    'stubble',
    'van dyke'
  ],
  'clothings': [
    'athletic',
    'casual',
    'tailored',
    'conservative',
    'eclectic',
    'colorful',
    'formal',
    'grungy',
    'headbanger',
    'hippy',
    'hipster',
    'mod',
    'nerdy',
    'new-wave',
    'prairie',
    'preppy',
    'punk',
    'retro-disco',
    'retro-fifties',
    'runway',
    'sloppy',
    'trendy'
  ],
  'piercings': [
    'a cheek piercing',
    'both ears pierced',
    'an ear (auricle) piercing',
    'an ear (conch) piercing',
    'both ears pierced, twice',
    'multiple ear piercings',
    'an eyebrow piercing',
    'a labret piercing',
    'a lip piercing',
    'a neck piercing',
    'a nose piercing',
    'a septum piercing',
    'a third eye piercing',
    'a tongue piercing',
    'a webbing piercing'
  ],
  'bodyparts1': [
    'abdomen',
    'back',
    'forehead',
    'scalp',
    'neck',
    'chin'
  ],
  'leftrights': [
    'left',
    'right'
  ],
  'bodyparts2': [
    'forearm',
    'upper arm',
    'wrist',
    'shoulder',
    'buttock',
    'chest',
    'foot',
    'cheek',
    'hand',
    'hip',
    'ankle',
    'calf',
    'thigh'
  ],
  'gestures': [
    'holds still when talking',
    'gestures dramatically',
    'gestures quickly',
    'makes subtle gestures',
    'twitchy',
    'fidgets constantly',
    'tends to make repetitive movements'
  ],
  'movements': [
    'limps',
    'has a long stride',
    'moves in a cautious/tense manner',
    'moves in a fast/controlled manner',
    'moves in a fast/jerky manner',
    'moves in a slow/clumsy manner',
    'moves in a slow/controlled manner',
    'has a short stride',
    'struts',
    'sashays',
    'has an uneven gait',
    'walks fast with a forward lean',
    'walks fast and upright',
    'walks slow and leans back',
    'walks slow and upright'
  ],
  'stances': [
    'hunches the shoulders',
    'has a military bearing',
    'is bowlegged',
    'has a contorted/twisted posture',
    'has a relaxed stance',
    'slouches',
    'stands with hips forward',
    'has a stiff/tense stance',
    'stands with the stomach relaxed',
    'stands with the stomach tensed',
  ],
  'disabilityphys': [
    'agnosia',
    'albinism',
    'aphasia',
    'apraxia',
    'severe arthritis',
    'a prosthetic arm',
    'a prosthetic hand',
    'a prosthetic leg',
    'auditory neuropathy',
    'impaired vision',
    'cerebral palsy',
    'impaired hearing',
    'dysarthria',
    'dysmetria',
    'dysphagia',
    'dysphonia',
    'an injury requiring crutches',
    'a disability that requires a walker',
    'a disability that requires a wheelchair',
    'lymphedema',
    'muscular dystrophy',
    'myotonic dystrophy',
    'paraplegia',
    'radial tunnel syndrome',
    'scoliosis',
    'spina bifida',
    'triparesis',
    'triplegia',
    'alzheimers',
    'asperger syndrome',
    'ADHD/ADD',
    'autism',
    'down syndrome',
    'dyscalculia',
    'dysgraphia',
    'dyslexia',
    'dyspraxia',
    'a stutter',
    'tourettes'
  ],
  'physkills': [
    'agility',
    'balance',
    'coordination',
    'dexterity',
    'flexibility',
    'reflexes',
    'speed',
    'stamina',
    'strength'
  ]
}
var mind = {
  'outlooks': [
    'optimistic',
    'pessimistic',
    'cynical',
    'idealistic',
    'realistic',
    'pragmatic'
  ],
  'attitudes': [
    'absent-minded',
    'adventurous',
    'agreeable',
    'aggressive',
    'ambitious',
    'analytical',
    'assertive',
    'awkward',
    'boastful',
    'bold',
    'bossy',
    'brilliant',
    'brusque',
    'calm',
    'careless',
    'cautious',
    'charming',
    'cheerful',
    'clever',
    'clingy',
    'compassionate',
    'competitive',
    'conceited',
    'confident',
    'confused',
    'considerate',
    'contemptuous',
    'courageous',
    'cowardly',
    'creative',
    'cruel',
    'curious',
    'daring',
    'demanding',
    'determined',
    'diplomatic',
    'disagreeable',
    'disapproving',
    'distrustful',
    'dull',
    'energetic',
    'excitable',
    'fearful',
    'fierce',
    'forgetful',
    'forgiving',
    'frantic',
    'friendly',
    'funny',
    'generous',
    'gentle',
    'gloomy',
    'greedy',
    'happy',
    'hard-working',
    'helpful',
    'honest',
    'humble',
    'imaginative',
    'impatient',
    'impulsive',
    'independent',
    'insensitive',
    'intelligent',
    'intimidating',
    'inventive',
    'irresponsible',
    'joyful',
    'kind',
    'laidback',
    'lazy',
    'loud',
    'lovable',
    'loyal',
    'messy',
    'mischievous',
    'nagging',
    'naive',
    'obedient',
    'outspoken',
    'passionate',
    'patient',
    'pedantic',
    'playful',
    'pleasant',
    'polite',
    'prim',
    'proper',
    'proud',
    'quarrelsome',
    'quick-tempered',
    'quiet',
    'reasonable',
    'reckless',
    'reliable',
    'reserved',
    'respectful',
    'responsible',
    'restless',
    'rude',
    'sad',
    'selfish',
    'sensitive',
    'sentimental',
    'serious',
    'sharp-witted',
    'shiftless',
    'shrewd',
    'shy',
    'simple-minded',
    'sneaky',
    'soft-hearted',
    'spunky',
    'stern',
    'stingy',
    'stubborn',
    'studious',
    'superstitious',
    'suspicious',
    'sycophantic',
    'talkative',
    'thoughtful',
    'timid',
    'tireless',
    'tough',
    'trusting',
    'ungrateful',
    'unpredictable',
    'unselfish',
    'weak-willed',
    'wild',
    'wise',
    'withdrawn',
    'witty',
    'zany'
  ],
  'conflicts': [
    'is a pure pacifist',
    'will only fight in defense',
    'is a reluctant fighter',
    'is a willing fighter',
    'will seek out and start fights'
  ],
  'conflictverbals': [
    'make peace, even if it means ignoring personal needs or not being heard',
    'attack first, often with threats that spiral into ultimatums',
    'use complaints, snark, or the silent treatment rather than direct confrontation',
    'avoid arguments, but if cornered will fight viciously and give no quarter',
    'negotiate to find a peaceful compromise',
    'freeze up and go silent, in hopes it will all go away'
  ],
  'emotions': [
    'anger',
    'fear',
    'hatred',
    'joy',
    'love',
    'lust',
    'regret',
    'sadness',
    'shame',
    'awe',
    'envy',
    'greed',
    'grief',
    'loneliness',
    'anxiety'
  ],
  'expressions': [
    'flares up but fades quickly',
    'builds slowly and lingers for awhile',
    'flares up and lingers afterwards',
    'is suppressed until it erupts in a dramatic fashion',
    'is internalized and reverse-projected',
    'is denied or dismissed',
    'is externalized and projected'
  ],
  'reactions': [
    'avoid conflict if possible',
    'skip the discussion and go directly to a physical confrontation',
    'keep any conflict purely verbal',
    'react in the manner attacked, whether verbal or physical'
  ]
};
var educations = [
  "no plans to continue",
  "plans to continue",
  "is currently a full-time student",
  "is currently on hiatus",
  "is currently studying part-time"
];
var schoolings = [
  "a high school-level",
  "an associates-level",
  "a bachelors-level",
  "masters-level",
  "a doctoratal-level",
  "no formal",
  "a fully self-taught",
  "a home-schooled"
];
var intelligences = [
  "functional",
  "below average",
  "average",
  "high",
  "above average",
  "genius-level"
];
var knowledges = [
  "is a beginner in almost all topics",
  "has a working knowledge of a limited set of topics",
  "has a working knowledge of a wide range of unrelated topics",
  "has considerable and deep knowledge of a few specific topics",
  "has comprehensive and broad knowledge across many unrelated topics",
  "is an expert on one or two specific topics",
  "is a comprehensive expert, knowledgable on many unrelated topics"
];
var faves = {
  'colors': [
    "black",
    "gray",
    "white",
    "cream",
    "tan",
    "brown",
    "dark yellow",
    "light yellow",
    "peach",
    "orange",
    "pink",
    "crimson",
    "maroon",
    "lilac",
    "mushroom",
    "royal purple",
    "indigo",
    "navy",
    "sky blue",
    "turqoise",
    "kelly green",
    "green",
    "lime"
  ],
  'days': [
    "pre-dawn",
    "dawn",
    "early morning",
    "late morning",
    "midday",
    "early afternoon",
    "late afternoon",
    "twilight",
    "late at night",
    "midnight",
    "small hours"
  ],
  'rooms': [
    "back deck",
    "back porch",
    "backyard",
    "bathroom",
    "bedroom",
    "courtyard",
    "den",
    "tv-room",
    "dining room",
    "front porch",
    "frontyard",
    "garage",
    "garden",
    "greenhouse",
    "hallway",
    "kitchen",
    "library",
    "living room",
    "office",
    "patio",
    "stairs",
    "art studio",
    "dance studio",
    "sewing studio",
    "sunroom",
    "tatami-room",
    "temple",
    "chapel",
    "family shrine",
    "workshop"
  ],
  'weathers': [
    "cold & dry",
    "cold & wet",
    "hot & dry",
    "hot & humid",
    "overcast",
    "hard rain",
    "soft rain",
    "blizzard",
    "light snow",
    "sunny & breezy",
    "after a thunderstorm",
    "before a thunderstorm",
    "thunderstorms",
    "light winds",
    "strong winds",
    "windy & damp",
    "light fog",
    "heavy fog",
    "misty"
  ],
  'holidays': [
    "amusement park",
    "art project",
    "backpacking",
    "beach, quiet",
    "big city",
    "biking",
    "bookstore",
    "bowling",
    "build something",
    "clothing store",
    "community work",
    "cruise",
    "dance club",
    "department store",
    "dirt/biker bar",
    "domestic city",
    "ethnic restaurant",
    "fine restaurant",
    "fix up house",
    "guided tours",
    "hometown",
    "job skill workshop",
    "library",
    "live music",
    "local bar",
    "mountains",
    "museum",
    "pay bills",
    "picnic",
    "roadtrip",
    "shoe store",
    "sightseeing",
    "skiing",
    "stay home",
    "surfing",
    "swap/hobbyist meet",
    "theater",
    "visit friends",
    "visit relatives",
    "visit the desert",
    "water park",
    "work on car/bike",
    "zoo"
  ],
  'seasons': [
    "early winter",
    "late winter",
    "early spring",
    "late spring",
    "early summer",
    "late summer",
    "early autumn",
    "late autumn"
  ],
  'environments': [
    "urban",
    "suburban",
    "rural",
    "wilderness",
    "large crowd",
    "small group",
    "alone"
  ]
};
var quirkmagis = [
  'Appears normal but unnerves animals; dogs bark, cats hiss, etc.',
  'Cannot be killed without a special ritual.',
  'Ice-cold to the touch when using magical skills.',
  'Feels feverish after using magical skills.',
  'Can paralyze a person or animal with a single touch.',
  'Addicted to a specific drink, and falls ill when deprived.',
  'Addicted to a specific food, and falls ill when deprived.',
  'Can alter the chemical make-up of any food or beverage and change it into some other food or beverage.',
  'Can become incorporeal.',
  'Can cause earthquakes.',
  'Can cause hurricane-like conditions.',
  'Can cause mutation in people or animals.',
  'Can cause thunderstorms.',
  'Can cause tornadoes.',
  'Can charm people into seeing them as sexy or attractive.',
  'Can communicate with resident spirits of rivers, oceans, lakes.',
  'Can communicate with resident spirits of trees, plants, or forests.',
  'Can communicate with rivers, oceans, lakes.',
  'Can communicate with someone by holding a picture of them.',
  'Can communicate with trees and plants.',
  'Can control anyone upon learning the person’s true name.',
  'Can create autonomous copies of themself.',
  'Can create illusions but mostly does it only for entertainment.',
  'Can create illusions but mostly does it only for subversive uses.',
  'Can create non-autonomous copies of themself.',
  'Can deliver an electrical shock by touch.',
  'Can draw sickness out of other people.',
  'Can focus a single sense to exponential levels.',
  'Can gain complete control over any muscles or organs in another person’s body.',
  'Can hear another world/plane in one ear.',
  'Can instantly imitate any skill after seeing it only once.',
  'Can interface mentally with any electrical network.',
  'Can levitate.',
  'Can fly.',
  'Can breathe underwater.',
  'Can locate any person, as long as they’ve met face-to-face.',
  'Can control other people’s speech.',
  'Can memorize entire books within fifteen minutes.',
  'Can pick up the history of a place from standing in it.',
  'Can read aura-trails and use them to predict a target’s next action.',
  'Can put people to sleep with a thought.',
  'Can see another world/plane out of one eye.',
  'Can see patterns and sequences and decrypt codes easily.',
  'Can see through others’ eyes via mild possession.',
  'Can summon invisible guards or scouts.',
  'Can turn invisible.',
  'Can tell if someone is lying just by listening to the person’s voice.',
  'Can think words onto paper.',
  'Can use enhanced hearing to track targets.',
  'Can use an enhanced sense of smell to track targets.',
  'Can use an enhanced sense of taste to track targets.',
  'Can use an enhanced sensitivity to earth to track targets.',
  'Can use an enhanced sensitivity to water to track targets.',
  'Can use water to speak with someone at a distance.',
  'Can use wind to speak with someone at a distance.',
  'Can use the earth to speak with someone at a distance.',
  'Can see aura-trails and use them to track a target.',
  'Can travel through dreams to transport self from one place to the next.',
  'Can travel through mirrors to transport self from one place to the next.',
  'Can travel through water to transport self from one place to the next.',
  'Can turn electronic appliances on and off with thoughts.',
  'Can walk through any terrain without leaving a trail, physical, or scent.',
  'Cannot be burned by fire.',
  'Immune to bladed weapons.',
  'Significantly impaired by injuries from weapons made of wood.',
  'Significantly impaired by injuries from weapon made of silver.',
  'Significantly impaired by injuries from weapons made of iron.',
  'Cannot cross any body of water at all.',
  'Cannot cross running water.',
  'Cannot cross water over a certain depth.',
  'Cannot stand the touch of metal.',
  'Cannot stand the touch of water.',
  'Cannot stand the touch of wood.',
  'Cannot talk to a desirable person without negative magical consequences.',
  'Cannot talk to a person of a different gender without negative magical consequences.',
  'Cannot talk to a person of the same gender without negative magical consequences.',
  'Cannot touch a desirable person without negative magical consequences.',
  'Cannot touch a person of a different gender without negative magical consequences.',
  'Cannot touch a person of the same gender without negative magical consequences.',
  'Can observe events at a distance while dreaming.',
  'Can discern future events based on personal dreams.',
  'Must personally pour their own drink, or suffer negative magical consequences.',
  'Must use a particular cup when drinking, or suffer negative magical consequences.',
  'Has bones that cannot break.',
  'Has complete muscular control over their body.',
  'Has several body parts that are can bend or flex in an unnatural or uncanny manner.',
  'Hypersensitive sense of smell, hearing, sight, etc.',
  'Can identify the last five people to handle an item just by holding that item.',
  'Powerless when the air is still or stuffy.',
  'Powerless when the humidity is over a certain point.',
  'Powerless when there’s a strong wind.',
  'Must personally cook all food eaten, or suffer negative magical consequences.',
  'Must use a specific plate or bowl to eat, or suffer negative magical consequences.',
  'Must use a specific utensil to eat, or suffer negative magical consequences.',
  'Cannot knowingly lie, even about small/harmless things, without suffering negative consequences.',
  'Can change aspects of their physical appearance.',
  'Can transform into an inanimate object.',
  'Can transform into a specific animal.',
  'Can transform into any sentient creature, for a limited time.',
  'Wears a particular piece of jewelry that can never be removed.',
  'Wears a particular piece of jewelry to prevent negative consequences.',
  'Wears a particular piece of jewelry to provide power.'
];
var quirks = [
  "Emotionless but fakes it well enough to fool everyone.",
  "Excessive Pollyanna.",
  "Gives attitude to everyone except to one or two specific people.",
  "Happiest when working in a crowded, noisy environment",
  "Hard worker, but without actual goals.",
  "Has a list of transgressions and a revenge appropriate for each.",
  "Has itchy scalp, elbows, stomach, etc; constantly scratching.",
  "Has never cut hair and/or shaved.",
  "Has no body hair below the shoulders.",
  "Has the attention span of a goldfish.",
  "Has variety of nicknames depending on social group.",
  "Hides cash in sock, shorts, bra, etc.",
  "Hums tunelessly when thinking, or when working on something.",
  "Hypersensitive sense of smell, hearing, sight, etc.",
  "Hypochondriac; always seeking cure for a disease or condition.",
  "insists on a different name each day, depending on mood.",
  "insists on butting into every single little problem.",
  "insists on sharing equally, but privately hoards the same item (food, money, etc).",
  "insomniac; going without sleep for several days at a time, and eventually showing the strain.",
  "Looks and acts stupid, but is a passionate master persuader.",
  "Loves to cook, but does it very badly.",
  "Loves to wear costume jewelry, tricked out clothing, etc.",
  "Makes fun of opponents by mimicking them.",
  "Masochist; enjoys pain.",
  "Messy but insists it's an organized chaos; knows where everything is, and can find it quickly.",
  "Must control everyone and everything.",
  "Names and becomes attached to stuffed animals, caterpillars, rocks, raindrops on the window, etc.",
  "Names and talks to all personal weapons.",
  "Never answers the door.",
  "Never answers the phone.",
  "Never asks for help; always tries to do everything independently.",
  "Never curses or uses a deity's name in vain. Disapproves of those who do.",
  "Never dodges oncoming pedestrians, forcing others to move out of the way instead.",
  "Never looks anyone in the eye.",
  "Never refuses a challenge, no matter how stupid it may be.",
  "Never sheaths a weapon until it's tasted blood.",
  "Never talks about the future.",
  "Never talks about the past.",
  "Nonpicky about lovers; happy with anyone.",
  "Nudist.",
  "Receives visions from smoke or steam.",
  "Refers to self in the third person.",
  "Regularly looks up at the sky to check the position of the sun/moon.",
  "Stacks books vertically, not horizontally.",
  "Stands with hands behind the back in at-ease position, regardless of any actual military experience.",
  "Strategist; always seems to have planned for any contingency.",
  "Submits to the ideas and suggestions of others without thinking of own needs.",
  "Suffers from short-term memory loss.",
  "Takes immediate and instinctive command of every emergency situation.",
  "Takes practical jokes very poorly.",
  "Takes stupid bets/dares for small amounts of money.",
  "Terrified of cats.",
  "Terrified of deep water.",
  "Terrified of dogs.",
  "Terrified of needles.",
  "Tone-deaf but loves to sing. Loudly.",
  "Treats everyone with respect, no matter their class or station.",
  "Unable to take advice without finding reason to insist it won't work.",
  "Very low self-esteem; suffers extreme self-doubt at the slightest criticism.",
  "When told no, it only strengthens resolve.",
  "Will accept almost anything as &ldquo;normal&rdquo;, once explained.",
  "Will deny/ignore own feelings as required, to avoid offending friends.",
  "Will deny/ignore own feelings as required, to avoid offending strangers.",
  "Willing to do anything for information.",
  "Terrified of not meeting parent, teacher, or deity expectations.",
  "Thinks up elaborate solutions then discards them for being too easily seen through.",
  "Thinks up elaborate solutions to simple problems.",
  "Oblivious to entire wardrobe being paint/chemical-spattered.",
  "Obsesses over specific body parts of potential lovers.",
  "Offended upon realizing that someone listened just to shut them up (and then didn't follow advice).",
  "Often busy mending broken objects, just to see if it can be done.",
  "Often drives at excessive speed, weaving in and out of traffic, without wrecking.",
  "Often forms an attachment to certain types of items (eg fine cars), even if owned by someone else, and feels slighted if the they are mistreated.",
  "Organizes important paperwork in stacks.",
  "Overprotective of younger friends; suspicious of friends' lovers.",
  "Overprotective of younger siblings; suspicious of siblings' friends/lovers.",
  "Personally offended when mail is misdelivered.",
  "Picks up trash that other people drop.",
  "Prefers computer sex to the real thing.",
  "Profusely sweats even when at rest.",
  "Raises chickens, pigs, etc.",
  "Readily gets in the way of danger if it's required to protect a loved one.",
  "Readily gets in the way of danger if it's required to protect anyone, including strangers.",
  "Readily lands in the way of danger without thinking first.",
  "Rude to everyone.",
  "Rude, but purely unintentionally.",
  "Sadist; enjoys dispensing pain.",
  "Short, but envies those who are tall.",
  "Tall, but envies those who are short.",
  "Absent-minded, losing glasses while still wearing them.",
  "Absolutely no sense of direction.",
  "Affectionate towards farm animals.",
  "Agrees with opponent at first, and changes mind later in private.",
  "Always finds an excuse not to tell a woman how he feels about her.",
  "Always finds the bright side of any disaster, however far-fetched.",
  "Always gets others to agree first to something he doesn't want in order to later get them to agree to what he does want.",
  "Always hugs full-body contact, regardless of relationship.",
  "Always hugs shoulders-only, regardless of relationship.",
  "Always knows the direction he or she is traveling in.",
  "Always needs to be the center of attention.",
  "Always replies to email/phone calls immediately.",
  "Always screens all calls.",
  "Always tidies up the table and resets the condiments when dining out.",
  "Always uses a handkerchief to touch a public telephone, chair, etc.",
  "Asks for exactly the same thing over and over, even after being told repeatedly that it's infeasible, impossible, unavailable, etc.",
  "Turned on by any name with a certain sound in it.",
  "Avoids specific songs due to connection with non-traumatic/trivial events.",
  "Avoids specific songs due to connection with traumatic events.",
  "Can determine how any device functions just by handling it briefly.",
  "Can only hear out of one ear.",
  "Can only see out of one eye.",
  "Can perform rapid mental calculations without effort.",
  "Can play any song after only hearing once.",
  "Can recite text in full after only hearing once.",
  "Can recite text in full after only reading once.",
  "Can repair anything mechanical with only a few minutes' study.",
  "Can replicate any sound, flawlessly.",
  "Can see patterns and sequences and decrypt codes easily.",
  "Can walk through any terrain without leaving a trail.",
  "Can't swallow pills.",
  "Cannot swim, and has no inclination to learn.",
  "Carries a full set of imperial ratcheting wrenches.",
  "Carries a good luck charm everywhere.",
  "Celebrates in rambunctious manner when plans are settled.",
  "Classist; doesn't admit publicly to having 'the wrong type' of friends.",
  "Clumsy, always breaks things, trips over things, etc.",
  "Constantly rescuing stray animals.",
  "Constantly scanning the faces of all strangers who walk past.",
  "Constantly sniffling despite being healthy.",
  "Constantly spitting.",
  "Constantly tweaks what already completed, to make it better.",
  "Constantly wants help with even the simplest tasks.",
  "Contradicts everyone about absolutely anything even the pointless things.",
  "Denies any fact that does not fit into personal theory of how things work.",
  "Depressed unless given a steady stream of positive feedback.",
  "Doesn't wash hands after using the bathroom.",
  "Dots i's with a smiley face or heart.",
  "Dreams, meaningful; is convinced every strange dreams is a portent.",
  "Drops trash without caring where it lands.",
  "Easily brought to tears over specific topics, but tries to hide it.",
  "Easily deceived by anyone who uses words he doesn't understand.",
  "Easily distracted by a particular type of person and will break off conversations and devote total attention to any of that type who show up.",
  "Easily swayed by food and money.",
];
var otherquirks = {
  "attires": [
    "Always wears a hat, scarf, or head-wrap.",
    "Considers a certain type of animal unclean and won't wear/use anything made from it.",
    "Refuses to wear glasses, even when badly needed.",
    "Unable to pass mirror or reflective surface without checking hair, makeup, personality.",
    "Wears a piece of jewelry constantly for specifically sentimental reasons."
  ],
  "beliefs": [
    "Constantly trying to recruit people to religious/philosophical beliefs.",
    "Does not believe in a deity, and scorns those who do.",
    "Intensely passionate about beliefs, strong temper if violated in some way.",
    "Professes multiple, incompatible religions.",
    "That God is a sham created by the clergy to get money.",
    "Believes they're part of some kind of prophecy.",
    "Tupperware parties, AA meetings, etc. are fronts for a massive conspiracy."
  ],
  "collections": [
    "Picks up little objects (keys, bottle caps, coins, etc), and leaves behind something else in replacement.",
    "Picks up little objects (keys, bottle caps, coins, etc), and always seems to lose something else at the same time.",
    "Collects rocks."
  ],
  "disdains": [
    "Disdainful of anyone who uses the imperial system.",
    "Disdainful of anyone who uses the metric system.",
    "Dislikes watching movies in movie-theaters.",
    "Distrusts and suspects anyone with a strong intuition.",
    "Distrusts anyone who refuses to doubt themselves.",
    "Distrusts own memory; compensates by being a compulsive note-taker.",
    "Distrusts people who can't remember names.",
    "Distrusts people who have a specific eye-color.",
    "Distrusts people who talk with an accent.",
    "Does not own, nor want to own, a television."
  ],
  "drinks": [
    "Accepts only specific brands of alcohol.",
    "Addicted to caffeine.",
    "Adores a specific drink, and gets upset when it's not available.",
    "Cannot drink anything with ice in it.",
    "Gives the first bite to deity/ancestors by setting it aside.",
    "Hates alcohol.",
    "Hates coffee.",
    "Paranoid about drinking anything not opened and poured personally.",
    "Refuses to drink straight from bottles.",
    "Refuses to drink straight from metal cans."
  ],
  "eats": [
    "Eats as if it's competition; learned to grab food quickly or go hungry.",
    "Often gets sick from overeating.",
    "Picky eater; willing to offend hosts/friends to avoid certain foods.",
    "Learned to eat fast due to never having enough time for a meal.",
    "Addicted to chocolate.",
    "Adores a specific food, and gets upset when it's not available.",
    "Chews tobacco.",
    "Chews with mouth open.",
    "Considers a certain type of animal unclean and won't eat it.",
    "Constantly sucking on a breath mint or candy.",
    "doesn't like when different kinds of food touch on the plate.",
    "Eats and smokes at the same time.",
    "Eats and talks at the same time.",
    "Gives the first sip to deity/ancestors by spilling it onto the ground.",
    "Hates chocolate.",
    "Hates vegetables.",
    "Only uses hands.",
    "Paranoid about eating food someone else cooked.",
    "Puts a specific condiment (ketchup, maple syrup, salt, mustard) on everything.",
    "Refuses to touch food with hands.",
    "Vegan for cultural reasons.",
    "Vegan for health reasons.",
    "Vegan for political reasons.",
    "Vegan for religious reasons.",
    "Vegetarian for cultural reasons.",
    "Vegetarian for health reasons.",
    "Vegetarian for political reasons.",
    "Vegetarian for religious reasons."
  ],
  "fidgets": [
    "Constantly tugging on a necklace, twisting it, etc.",
    "Constantly tugging on earrings, or removing and replacing.",
    "Constantly undoing and tightening or loosening watch.",
    "Twists a ring around the finger, repeatedly.",
    "Bites nails to the quick.",
    "Constantly chewing on non-food (toothpick, pen-cap, lollipop-stick).",
    "Constantly cleaning spectacles or pushing them up their nose.",
    "Constantly doodling in margins of papers, books, etc.",
    "Constantly touches face or head.",
    "Fidgety, with nervous twitches in hands, eyes, feet.",
    "Picks at own skin, hair, clothing, or teeth obsessively when tense.",
    "Restless, always has leg or hand tapping or moving."
  ],
  "finances": [
    "Always has pocket change to give to beggars or homeless.",
    "Always has the precise amount of money to purchase any specific thing.",
    "Generous with money even when unable to afford being so.",
    "Refuses to pay more than the barest amount required for accommodations, even if that means staying at a roach motel.",
    "Thrifty almost to the point of obsession."
  ],
  "greets": [
    "Greets acquaintances by kissing both cheeks.",
    "Greets acquaintances by kissing one cheek.",
    "Greets acquaintances with a bow.",
    "Greets acquaintances with a handshake.",
    "Greets acquaintances with a hug.",
    "Greets acquaintances with a simple nod.",
    "Greets enthusiastically rambunctious upon meeting someone for the first time.",
    "Greets friends by kissing both cheeks.",
    "Greets friends by kissing one cheek.",
    "Greets friends with a handshake.",
    "Greets friends with a simple nod.",
    "Greets new-met friend by kissing both cheeks.",
    "Greets new-met friend by kissing one cheek.",
    "Greets new-met friend with a bow.",
    "Greets new-met friend with a hug.",
    "Greets new-met friend with a nod.",
    "Greets refuses to shake hands for any reason."
  ],
  "hands": [
    "Near-ambidextrous, able to perform many tasks with either hand.",
    "Writes with the dominant hand, does everything else with the other hand."
  ],
  "hates": [
    "Hates children.",
    "Hates clothes left lying around.",
    "Hates doing the same thing day after day.",
    "Hates having name mispronounced.",
    "Hates having name misspelled.",
    "Hates messy rooms; becomes furious if forced to spend time in one.",
    "Hates messy rooms; will start cleaning regardless of situation.",
    "Hates putting clothes away.",
    "Hates the sound of chewing.",
    "Hates to be photographed.",
    "Hates to clean anything.",
    "Hates to cook, but is actually a very good cook.",
    "Hates to do laundry.",
    "Hates to sweat, and is turned off by people who sweat profusely.",
    "Hates to wash dishes.",
    "Violent reaction if approached from behind without warning.",
    "Violent reaction if hugged by someone not given 'permission' to do so.",
    "Violent reaction if hugged without warning."
  ],
  "humors": [
    "Never smiles.",
    "Treats every joke as though it were serious.",
    "Will go overboard getting people to laugh even in a serious situation.",
    "Smiles even when the situation is serious.",
    "Laughs at the wrong things.",
    "Deadpan humor to the point even friends aren't certain what's serious and what's meant in humor."
  ],
  "literacys": [
    "Can read only simple words and identify numbers.",
    "Struggles with reading anything quickly that's longer than a one or two word common phrase.",
    "Reads every newspaper and website; watches every news program."
  ],
  "intuitions": [
    "Instantly knows what others feel, and is always wrong.",
    "Instantly knows what others feel."
  ],
  "laws": [
    "Obeys even stupid laws, unless has compelling reason not to.",
    "Breaks even intelligent laws unless has compelling reason not to.",
    "Compelled to break any law at least once."
  ],
  "lies": [
    "Habitual liar; lies just for the sake of lying, and to see if he can get away with it and/or fool everyone successfully.",
    "Manipulative liar: Doesn't precisely lie so much as use word-choice and tone to imply a meaning that may not exist in the actual words. See also, politician.",
    "Pathological liar: lies even when he doesn't want to, or doesn't intend to.",
    "Random liar; lies about unimportant things for no reason."
  ],
  "weathers": [
    "Miserable when the air is still or stuffy.",
    "Miserable when the humidity is over a certain point.",
    "Miserable when there's a strong wind."
  ],
  "sleeps": [
    "Nightmares, abrupt; wakes with a terrified jolt and soaked in sweat.",
    "Nightmares, loud: Dramatic, wakes with yell or specific cry.",
    "Nightmares, soft: Comes awake slowly, while crying.",
    "Nightmares, strangled: Can't wake from nightmare, except by forcing out sounds in hopes someone will wake him.",
    "Falls asleep when temperature drops below a certain point.",
    "Gets sluggish when temperature drops below a certain point.",
    "Requires 9+ hours of sleep a night to function well.",
    "Heavy sleeper; blasting caps won't even wake the person.",
    "Falls asleep when temperature rises above a certain point.",
    "Gets sluggish when temperature rises above a certain point.",
    "Light sleeper; wakes at the slightest crack or pop.",
    "Doesn't need more than 3-4 hours of sleep to function well.",
    "Picky sleeper; cannot sleep in a waterbed.",
    "Picky sleeper; cannot sleep on the floor, or near-floor level.",
    "Picky sleeper; only sleeps in a hammock.",
    "Picky sleeper; only sleeps well on the floor.",
    "Picky sleeper; sleeps best sitting up.",
    "Picky sleeper; won't sleep under the window.",
    "Restles sleeper; icks, tosses, turns, and flails all night long.",
    "Falls asleep and gets up at the same time every day."
  ],
  "refuses": [
    "Refuses to cross high bridges; gets someone else to drive for the duration.",
    "Refuses to cross water over a certain depth.",
    "Refuses to fight with anyone already injured.",
    "Refuses to fight with anyone smaller than himself.",
    "Refuses to fight with anyone wearing glasses.",
    "Refuses to fight with anyone of a different gender.",
    "Refuses to hug even good friends.",
    "Refuses to jaywalk except under extreme circumstances.",
    "Refuses to respect anyone until the respect is fully earned.",
    "Refuses to see flaws in loved ones.",
    "Refuses to see positive attributes in disliked people.",
    "Refuses to stay at anything less than 5-star hotel.",
    "Refuses to stop and ask for directions. At all. Ever.",
    "Refuses to use a cell phone.",
    "Refuses to use a computer.",
    "Refuses to use a microwave."
  ],
  "relates": [
    "Relates everything to a fable or allegory.",
    "Relates everything to books, ie, is reminded of X scene from Y book.",
    "Relates everything to movies, ie, is reminded of X scene from Y movie.",
    "Relates everything to specific songs, ie, is reminded of X lyric or Y album."
  ],
  "relaxings": [
    "Relaxes by being alone and playing an instrument.",
    "Relaxes by being around close friends even if not interacting with them (in the same room while reading a book, etc).",
    "Relaxes by joining a large crowd of strangers and making friends.",
    "Relaxes by sitting out in public and people-watching."
  ],
  "speechs": [
    "Always shouts a specific phrase when startled.",
    "Always talks in a monotone voice.",
    "Blurts out thoughts, and reconsiders afterwards.",
    "Brags about past accomplishments, even made-up ones.",
    "Cannot stick to conversational topic; always gets off on a tangent, tirade, etc.",
    "Cannot talk to a desirable person without making a physical gaffe.",
    "Cannot talk to a desirable person without making a verbal gaffe.",
    "Cannot talk to a person of the opposite gender without making a gaffe.",
    "Cannot talk to a person of the same gender without making a physical gaffe.",
    "Cannot talk to a person of the same gender without making a verbal gaffe.",
    "Compulsively points out and corrects mistakes when related to personal expertise, even mistakes made by strangers.",
    "Corrects people when they use colloquial speech/slang.",
    "Ends declarative sentences with in interrogative inflection?",
    "Enjoys arguing but can't figure out why no one will do it with him.",
    "Extremely annoyed when people mispronounce a certain word.",
    "Frequently makes double-entendres or Freudian slips.",
    "Hates mispronouncing personal names; will avoid using a name altogether if unable to get the sound right.",
    "Mispronounces a certain word or uses redundant terms.",
    "Mush mouth, doesn't enunciate.",
    "Often makes malapropisms or spoonerisms.",
    "Quotes adages even if irrelevant.",
    "Quotes favorite movies and can usually identify the movie that a quote may come from.",
    "Rattles on about trivia when there are significant matters to discuss.",
    "Refuses to talk in presence of anyone who is 'mixed', ie, half-___.",
    "Renames everything he comes across.",
    "Speaks in a dignified, formal tone, even in casual conversation.",
    "Talks to weapon before fighting.",
    "Tells the truth even when a small lie would be wiser.",
    "Tells the truth even when silence would be wiser.",
    "Tells the truth even when to own detriment.",
    "Uses acronyms or jargon and doesn't bother to explain.",
    "When stressed or lying, speaks from the corner of the mouth.",
    "Takes every reaction as a compliment.",
    "Takes every reaction as a criticism."
  ],
  "storys": [
    "Compulsively interrupts people telling stories to interject facts known only from hearing the story before, and not because of first-hand knowledge.",
    "Constantly creating stories about any nearby strangers.",
    "Constantly creating stories about any nearby strangers and telling those stories loud enough for the strangers to also hear.",
    "Steals anecdotes and retells them as if their own.",
    "Steals anecdotes, retells them as if their own, and doesn't remember the original source, sometimes even tells someone's story back to them."
  ],
  "times": [
    "At least ten minutes early to any appointment.",
    "At least ten minutes late to any appointment.",
    "Constantly checking the time.",
    "On time to high-priority appointments but otherwise constantly running late."
  ]
}
var names = {
  'one': [
    'Andrey',
    'Bishal',
    'Cai',
    'Diego',
    'Eino',
    'Francisco',
    'Gan',
    'Heloísa',
    'Athanasios',
    'Ji-woo',
    'Kirill',
    'Lamija',
    'Maia',
    'Nia',
    'Arsen',
    'Bi',
    'Chedeline',
    'Dunja',
    'Evgeny',
    'Freja',
    'Gustavs',
    'Hans',
    'Islande',
    'Joannis',
    'Kamilė',
    'Liepa',
    'Moussa',
    'Noemi',
    'Omri',
    'Pavle',
    'Rita',
    'Siti',
    'Tamilla',
    'Aruzhan',
    'Brandur',
    'Constantina',
    'Dhia',
    'Enzo',
    'Fozia',
    'Victor',
    'Hana',
    'Malen',
    'Julen',
    'Khaled',
    'Lucia',
    'Mikita',
    'Nomaan',
    'Yahli',
    'Pedro',
    'Rabina',
    'Susanna',
    'Tigran',
    'Abdel',
    'Bandar',
    'Chae-won',
    'De',
    'Emir',
    'Fynn',
    'Georgia',
    'Hong',
    'Ivana',
    'João',
    'Kamila',
    'Leen',
    'Marama',
    'Na',
    'Yassin',
    'Shu-hua',
    'Roan',
    'Saba',
    'Michaela',
    'Assil',
    'Ashley',
    'Carl',
    'Abbas',
    'Emilia',
    'Fenna',
    'Vicente',
    'Himari',
    'Myrlande',
    'Justin',
    'Kejsi',
    'Luuk',
    'Maeva',
    'Anastasia',
    'Anar',
    'Sultan',
    'Alfred',
    'Serife',
    'Althea',
    'Alexander',
    'Bruno',
    'Somsak',
    'Dong',
    'Elijah',
    'Zara',
    'Valeria',
    'Hinano',
    'Aina',
    'Jayden',
    'Agustín',
    'Levi',
    'Mihajlo',
    'Nika',
    'Oisha',
    'Poema',
    'Rasmus',
    'Setayesh',
    'Tatiana',
    'Matthew',
    'Bibek',
    'Christina',
    'Dimitra',
    'Elsa',
    'Fahad',
    'Vivaan',
    'Hasnaa',
    'Iñkär',
    'Javier',
    'Kobe',
    'Laura',
    'Mariam',
    'Naranbaatar',
    'Osman',
    'Wout',
    'Rawiri',
    'Seo-jun',
    'Teodora',
    'Aygun',
    'Biel',
    'Snezana',
    'Xian',
    'Elena',
    'Fien',
    'Aino',
    'Hosniya',
    'Inès',
    'Jing',
    'Kaia',
    'Lin',
    'Marta',
    'Nazar',
    'Oumar',
    'Peng',
    'Raquel',
    'Samkelo',
    'Tarita',
    'Melokuhle',
    'Blanca',
    'Celine',
    'Abdulaziz',
    'Eva',
    'Žan',
    'Vedad',
    'Hasti',
    'Ida',
    'Jordi',
    'Kyriaki',
    'Levente',
    'Maite',
    'Nur',
    'Ólafur',
    'Panagiotis',
    'Ronja',
    'Sezim',
    'Ting',
    'Manon',
    'Bogdan',
    'Chun-hung',
    'Xia',
    'Evens',
    'Faisal',
    'Gunay',
    'Hannah',
    'Ahmed',
    'Jonathan',
    'Katrín',
    'Leandra',
    'Martina',
    'Nik',
    'Ugnė',
    'Wilma',
    'Rachid',
    'Sō',
    'Tobias',
    'Aziz',
    'Belinay',
    'Samir',
    'Dylan',
    'Ethan',
    'Felix',
    'Vesna',
    'Holly',
    'Ilgar',
    'Joel',
    'Kamal',
    'Lore',
    'Anđela',
    'Ayaan',
    'Abubakr',
    'Aisha',
    'Abdul',
    'Sanzhar',
    'Adi',
    'Myra',
    'Bayarmaa',
    'Sevinj',
    'Dominique',
    'Ela',
    'Fatin',
    'Vasiliki',
    'Ha-yoon',
    'I-chun',
    'Jesse',
    'Konul',
    'Leo',
    'Malik',
    'Nicolas',
    'Yağmur',
    'Wakana',
    'Riya',
    'Salma',
    'Tapuarii',
    'Moeata',
    'Maha',
    'Sergei',
    'Daria',
    'Eevi',
    'Abed',
    'Grace',
    'Hina',
    'Itai',
    'Joaquín',
    'Kaiden',
    'Lulwa',
    'Mina',
    'Niharika',
    'Oier',
    'Wei',
    'Reihaneh',
    'Sahar',
    'Tunar'
  ],
  'two': [
    'Yi',
    'Shu-chen',
    'Anaya',
    'Stefan',
    'Tia',
    'Azuna',
    'Bismah',
    'Aarav',
    'Djamel',
    'Aykhan',
    'Antonella',
    'Gunel',
    'Hosna',
    'Indira',
    'Aron',
    'Malthe',
    'Cheng',
    'Amir',
    'Emina',
    'Abdelkader',
    'Seo-hyeon',
    'Haruki',
    'Inuk',
    'Amïna',
    'Abdulrahman',
    'Louise',
    'Nürasyl',
    'Qiong',
    'Patricia',
    'Roghayyeh',
    'Salomé',
    'Thalia',
    'Ataahua',
    'Barbara',
    'Chiara',
    'Davit',
    'Eymen',
    'Zainab',
    'Vasileios',
    'Hoda',
    'Ibai',
    'Jessica',
    'Kajus',
    'Lana',
    'Murad',
    'Natalia',
    'Yuval',
    'Pablo',
    'Reza',
    'Santino',
    'Turki',
    'Maui',
    'Boglárka',
    'Carla',
    'Diana',
    'Elchin',
    'Aylin',
    'Georgios',
    'Helmi',
    'İsmail',
    'Josefine',
    'Khongordzol',
    'Lavi',
    'Molly',
    'Naima',
    'Odval',
    'Petra',
    'Ró',
    'Shayma',
    'Tamir',
    'Amaira',
    'Bintou',
    'Chien-hung',
    'Dalal',
    'Eyal',
    'Fernanda',
    'Vihaan',
    'Hao',
    'Mahdi',
    'June',
    'Karima',
    'Lia',
    'Manua',
    'Nadia',
    'Ughur',
    'Pihla',
    'Reem',
    'Shi-woo',
    'Tarana',
    'Arjun',
    'Basiliki',
    'Camille',
    'Artem',
    'Edith',
    'Fatma',
    'Alexis',
    'Hiro',
    'Ihaia',
    'Jie',
    'Kaede',
    'Liisa',
    'Manuel',
    'Nahia',
    'Ori',
    'Pol',
    'Ramona',
    'Suha',
    'Thomas',
    'Abigail',
    'Melisa',
    'Anahit',
    'Aoi',
    'Eetu',
    'Farida',
    'Victoria',
    'Hatice',
    'Iva',
    'Jada',
    'Adel',
    'Lotte',
    'Moea',
    'Nürislam',
    'Omar',
    'Somayyeh',
    'Aya',
    'Mei-ling',
    'Angela',
    'Biljana',
    'Chin-lung',
    'Aurora',
    'Eliza',
    'Zeinab',
    'Vusal',
    'Haruto',
    'Ibrahim',
    'James',
    'Kang',
    'Lars',
    'Mona',
    'Ning',
    'Uxue',
    'Paninnguaq',
    'Rodrigo',
    'Shu',
    'Tianna',
    'Ayesha',
    'Bernardo',
    'Connor',
    'Sebastián',
    'Elias',
    'Fang',
    'Gamila',
    'Hessa',
    'Inunnguaq',
    'Julia',
    'Khawla',
    'Liam',
    'Mari',
    'Noam',
    'Ondřej',
    'Pipaluk',
    'Richard',
    'Sheikha',
    'Manaia',
    'Aysel',
    'Banele',
    'Amelia',
    'Denys',
    'Ajla',
    'Allan',
    'Vaea',
    'Hussa',
    'Izaro',
    'Jovan',
    'Kevin',
    'Laia',
    'Mathias',
    'Nemanja',
    'Urtė',
    'Panagiota',
    'Ruby',
    'Saqib',
    'Teura',
    'Aroha',
    'Balázs',
    'Said',
    'Daniel',
    'Ella',
    'Zoe',
    'Greta',
    'Hunter',
    'Irene',
    'Jan',
    'Kathem',
    'Lily',
    'Margaret',
    'Nela',
    'Yūto',
    'Somchai',
    'Ava',
    'Sophia',
    'Milana',
    'Agustina',
    'Bilal',
    'Shu-chuan',
    'Dovydas',
    'Esperanza',
    'Zala',
    'Alicia',
    'Harrison',
    'Itsuki',
    'Jun',
    'Katarina',
    'Linda',
    'Maša',
    'Andrea',
    'Oyunbileg',
    'Seo-yeon',
    'Alexandra',
    'Simon',
    'Mareva',
    'Alonso',
    'Brahim',
    'Sillin',
    'Asmita',
    'Eric',
    'Aqil',
    'Väinö',
    'Ali',
    'Adin',
    'Jeanne',
    'Kristina',
    'Liang',
    'Magnus',
    'Noor',
    'Olav',
    'Puteri',
    'Rachida',
    'Sherifa',
    'Teiva'
  ],
  'three': [
    'Jaka',
    'Kayden',
    'Leyla',
    'Mustafa',
    'Nina',
    'Yasmine',
    'Wiremu',
    'Rania',
    'Shan',
    'Thiago',
    'Mei',
    'Manish',
    'Catherine',
    'Dagur',
    'Adrian',
    'Bin',
    'Sukhbaаtar',
    'Anja',
    'Edel',
    'Artiom',
    'Gita',
    'Hamza',
    'Anahera',
    'Jackson',
    'Kauri',
    'Layla',
    'Majd',
    'Noah',
    'Youssef',
    'Paraskevi',
    'Riko',
    'Saga',
    'Taha',
    'Mahesh',
    'Brianna',
    'Chloe',
    'Do-yoon',
    'Eden',
    'Zahid',
    'Gamalat',
    'Hayato',
    'Inzhu',
    'Joo-won',
    'Kimmernaq',
    'Lesedi',
    'Marcell',
    'Alysha',
    'Ariel',
    'Seo-yun',
    'Aoife',
    'Santiago',
    'Aaron',
    'Adam',
    'Mabel',
    'Chih-ming',
    'Abdallah',
    'Elif',
    'Fanta',
    'George',
    'Hugo',
    'Ingrid',
    'Janine',
    'Khadija',
    'Leah',
    'Miguel',
    'Naasunnguaq',
    'Olga',
    'Stanley',
    'Anton',
    'Sita',
    'Mark',
    'Aidan',
    'Bandile',
    'Concepción',
    'Alisa',
    'Esther',
    'Feng',
    'Gabriela',
    'Habiba',
    'Igor',
    'Jana',
    'Khrystyna',
    'Lewis',
    'Matilde',
    'Nivi',
    'Yaraslaŭ',
    'Shu-hui',
    'Reyansh',
    'Somporn',
    'Miral',
    'Ana',
    'Beshoi',
    'César',
    'Daisy',
    'Elnur',
    'Zachary',
    'Gun-woo',
    'Hui',
    'Ian',
    'Joseph',
    'Kacper',
    'Anas',
    'Avery',
    'Adama',
    'Angel',
    'Ashraqat',
    'Awa',
    'Sakura',
    'Alikhan',
    'Modibo',
    'Bolormaa',
    'Chih-chiang',
    'Aaradhya',
    'Emmanuel',
    'Fajr',
    'Googoosh',
    'Heitor',
    'Imran',
    'Juan',
    'Kheira',
    'Luz',
    'Mamadou',
    'Nathaniel',
    'Yun-seo',
    'Prasert',
    'Rin',
    'Shu-fen',
    'Thandolwethu',
    'Arata',
    'Benedikt',
    'Christos',
    'Alva',
    'Eliise',
    'Florencia',
    'Guo',
    'Harper',
    'Milan',
    'Jun-seo',
    'Kabita',
    'Lei',
    'Mohamed',
    'Nora',
    'Ai',
    'Sunita',
    'Alesia',
    'Samuel',
    'Androula',
    'An',
    'Bo',
    'Carlota',
    'Ximena',
    'Eun-seo',
    'Fatoumata',
    'Vojtěch',
    'Hyun-woo',
    'Ichika',
    'Julian',
    'Kadiatou',
    'Lan',
    'Mahmoud',
    'Aadya',
    'Ying',
    'Paula',
    'Rani',
    'Seán',
    'Tsimafei',
    'Ani',
    'Binita',
    'Shanaya',
    'Doha',
    'Elizabeth',
    'Alaksiej',
    'Gang',
    'Hinata',
    'Iker',
    'Judeline',
    'Käwsar',
    'Lovely',
    'Mei-hui',
    'Nuray',
    'Amanda',
    'Ayaulym',
    'Anohito',
    'Sarah',
    'Ajna',
    'Amit',
    'Berat',
    'Charbel',
    'Djeneba',
    'Ammar',
    'Zoran',
    'Gor',
    'Heikapu',
    'Maximilian',
    'Jaxon',
    'Krishna',
    'Li-hua',
    'Mïras',
    'Nesreen',
    'Yerasyl',
    'Wojciech',
    'Rimas',
    'Sekou',
    'Teiki',
    'Ajani',
    'Mary',
    'Catalina',
    'Dejan',
    'Ane',
    'Zhen',
    'Viltė',
    'Hayk',
    'Isabel',
    'Jian',
    'Kyrylo',
    'Lucas',
    'Mason',
    'Nareh',
    'Umar',
    'William',
    'Ramón',
    'Sumayah',
    'Tala',
    'Miyar',
    'Bahah',
    'Chun-chieh',
    'Xhoel',
    'Elen',
    'Aimar',
    'Violeta',
    'Haruta',
    'Irati',
    'Jacob',
    'Kanata',
    'Lethabo',
    'Mirlande',
    'Nurul',
    'Oumou',
    'Peter',
    'Ryō',
    'Shristi',
    'Théo'
  ],
  'four': [
    'Emil',
    'Finn',
    'Valentina',
    'Hekla',
    'Abdoulaye',
    'Joshua',
    'Kseniya',
    'Leia',
    'Mehmet',
    'Narek',
    'Yonatan',
    'Prem',
    'Rowan',
    'Sōta',
    'Tareq',
    'Aline',
    'Minik',
    'Shaimaa',
    'Dorothy',
    'Elshan',
    'Aada',
    'Guilherme',
    'Halim',
    'Izz',
    'Joanna',
    'Katrina',
    'Leonor',
    'Moana',
    'Nino',
    'Yuuma',
    'Prakash',
    'Ralfs',
    'Shaikha',
    'Tatsuki',
    'Azra',
    'Malika',
    'Carolina',
    'Darius',
    'Aksel',
    'Fadi',
    'Vugar',
    'Asahi',
    'Sandra',
    'Ji-hoon',
    'Kai',
    'Lior',
    'Milagrosa',
    'Niilo',
    'Yarin',
    'Sai',
    'Rósa',
    'Somboon',
    'Tao',
    'Austėja',
    'Mia',
    'Chuluun',
    'Dragan',
    'Eitan',
    'Fabian',
    'Vid',
    'Hassan',
    'Abril',
    'Jod',
    'Kirollos',
    'Louis',
    'Milica',
    'Nicole',
    'Oliver',
    'Wen',
    'Robin',
    'Souleymane',
    'Tehei',
    'Alma',
    'Bakary',
    'Clara',
    'Diya',
    'Ema',
    'Farah',
    'Ma’ayan',
    'Hasan',
    'Amar',
    'Jovana',
    'Kaspar',
    'Lívia',
    'Maksim',
    'Neža',
    'Yan',
    'Salik',
    'Ren',
    'Siyabonga',
    'Taichi',
    'Adele',
    'Batkhaаn',
    'Charlotte',
    'Dulce',
    'Eisha',
    'Francis',
    'Vuk',
    'Habib',
    'Illya',
    'Ji-ah',
    'Amahle',
    'Lee',
    'Maciej',
    'Ni',
    'Onni',
    'Shahid',
    'Rókur',
    'Selim',
    'Marti',
    'Atharv',
    'Martin',
    'Charles',
    'Amaia',
    'Emmanuela',
    'Amal',
    'Gabija',
    'Haruhito',
    'Isla',
    'Jun',
    'Klea',
    'Leon',
    'Mehdi',
    'Noel',
    'Qian',
    'Shira',
    'Arman',
    'Susan',
    'Manaaki',
    'Alba',
    'Minato',
    'Carmen',
    'Dominik',
    'Aicha',
    'Advik',
    'Vusala',
    'Hossein',
    'Ivan',
    'José',
    'Karim',
    'Lena',
    'Milagros',
    'Nuka',
    'Yael',
    'Stella',
    'Raya',
    'Salman',
    'Min-jun',
    'Ari',
    'Bader',
    'Chia-hao',
    'Daniela',
    'Ebba',
    'Zahra',
    'Gunnar',
    'Hsiung',
    'Ivalu',
    'Jakob',
    'Kristín',
    'Leevi',
    'Min-seo',
    'Nojus',
    'Oscar',
    'Palina',
    'Rosalie',
    'Saanvi',
    'Tamatoa',
    'Aputsiaq',
    'Béatrice',
    'Chih-hao',
    'Andre',
    'Ecrin',
    'Frederik',
    'Venla',
    'Henry',
    'Isidora',
    'Jonas',
    'Kora',
    'Lazar',
    'Mila',
    'Nisanur',
    'Unax',
    'Paul',
    'Rayan',
    'Sevda',
    'Tiare',
    'Michael',
    'Baаtar',
    'Constantinos',
    'Xinyi',
    'Esma',
    'Fatima',
    'Aminata',
    'Hawa',
    'Marwa',
    'Jude',
    'Ariana',
    'Lorena',
    'Maneh',
    'Nil',
    'Ullyana',
    'Sakineh',
    'Ann',
    'Samantha',
    'Minenhle',
    'Aisültan',
    'Benjamin',
    'Chih-wei',
    'Dmitry',
    'Arthur',
    'Farzana',
    'Goran',
    'Harun',
    'Aasha',
    'Jázmin',
    'Kostas',
    'Li',
    'Madina',
    'Narges',
    'Yahor',
    'Pau',
    'Roel',
    'Siddhartha',
    'Tomoharu',
    'Alice',
    'Sienna',
    'Carlos',
    'Daan',
    'Ergi',
    'Ayaru',
    'Gabriel',
    'Hydar',
    'Maisie',
    'Jean',
    'Kiran',
    'Lian',
    'Mobina',
    'Nehir',
    'Usman',
    'Polina',
    'Rafael',
    'Sem',
    'Teva'
  ]
};
</script>
